### ISSUE TITLE
"ipcluster nbextension enable" crashes on a permission error

### ISSUE THREAD

**Issue by znmeb** [ipython/ipyparallel#170]
Fedora 24, 64-bit, using Fedora's virtualenvwrapper. Here's the install code:

```
source ${VIRTUALENVWRAPPER_SCRIPT}
mkvirtualenv -p /usr/bin/python3 jupyter
workon jupyter

pip3 install --upgrade pip
pip3 install "jupyter"
pip3 install "ipyparallel"

# IJulia kernel
which jupyter
julia -E 'Pkg.add("IJulia")'
julia -E 'Pkg.build("IJulia")'

# R kernel
R -e 'IRkernel::installspec()'
```

But when I do `ipcluster nbextension enable` it looks like it's trying to write in `/usr`:

```
(jupyter) $ ipcluster nbextension enable
Enabling IPython clusters tab
Traceback (most recent call last):
  File "/home/znmeb/.virtualenvs/jupyter/bin/ipcluster", line 11, in <module>
    sys.exit(launch_new_instance())
  File "/home/znmeb/.virtualenvs/jupyter/lib/python3.5/site-packages/traitlets/config/application.py", line 596, in launch_instance
    app.start()
  File "/home/znmeb/.virtualenvs/jupyter/lib/python3.5/site-packages/ipyparallel/apps/ipclusterapp.py", line 635, in start
    return self.subapp.start()
  File "/home/znmeb/.virtualenvs/jupyter/lib/python3.5/site-packages/ipyparallel/apps/ipclusterapp.py", line 600, in start
    install_extensions(enable=True)
  File "/home/znmeb/.virtualenvs/jupyter/lib/python3.5/site-packages/ipyparallel/nbextension/install.py", line 25, in install_extensions
    install_nbextension_python('ipyparallel')
  File "/home/znmeb/.virtualenvs/jupyter/lib/python3.5/site-packages/notebook/nbextensions.py", line 239, in install_nbextension_python
    destination=dest, logger=logger
  File "/home/znmeb/.virtualenvs/jupyter/lib/python3.5/site-packages/notebook/nbextensions.py", line 140, in install_nbextension
    ensure_dir_exists(nbext)
  File "/home/znmeb/.virtualenvs/jupyter/lib/python3.5/site-packages/ipython_genutils/path.py", line 167, in ensure_dir_exists
    os.makedirs(path, mode=mode)
  File "/home/znmeb/.virtualenvs/jupyter/lib64/python3.5/os.py", line 231, in makedirs
    makedirs(head, mode, exist_ok)
  File "/home/znmeb/.virtualenvs/jupyter/lib64/python3.5/os.py", line 241, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: '/usr/local/share/jupyter'

If you suspect this is an IPython bug, please report it at:
    https://github.com/ipython/ipython/issues
or send an email to the mailing list at ipython-dev@scipy.org

You can print a more detailed traceback right now with "%tb", or use "%debug"
to interactively debug it.

Extra-detailed tracebacks for bug-reporting purposes can be enabled via:
    c.Application.verbose_crash=True

```

This looks like an installation problem but I don't know the Python ecosystem well enough to troubleshoot any further.

**Comment by hainm** [comment]
may be you can try `ipcluster nbextension enable --user`

**Comment by znmeb** [comment]
```
$ ipcluster nbextension enable --user
Enable/disable IPython clusters tab in Jupyter notebook

for Jupyter Notebook >= 4.2, you can use the new nbextension API:

jupyter serverextension enable --py ipyparallel jupyter nbextension install --py
ipyparallel jupyter nbextension enable --py ipyparallel

Options
-------

Arguments that take values are actually convenience aliases to full
Configurables, whose aliases are listed on the help line. For more information
on full configurables, see '--help-all'.

--init
    Initialize profile with default config files.  This is equivalent
    to running `ipython profile create <profile>` prior to startup.
--debug
    set log level to logging.DEBUG (maximize logging output)
--quiet
    set log level to logging.CRITICAL (minimize logging output)
--profile-dir=<Unicode> (ProfileDir.location)
    Default: ''
    Set the profile location directly. This overrides the logic used by the
    `profile` option.
--log-level=<Enum> (Application.log_level)
    Default: 30
    Choices: (0, 10, 20, 30, 40, 50, 'DEBUG', 'INFO', 'WARN', 'ERROR', 'CRITICAL')
    Set the log level by value or name.
--profile=<Unicode> (BaseIPythonApplication.profile)
    Default: 'default'
    The IPython profile to use.
--ipython-dir=<Unicode> (BaseIPythonApplication.ipython_dir)
    Default: ''
    The name of the IPython directory. This directory is used for logging
    configuration (through profiles), history storage, etc. The default is
    usually $HOME/.ipython. This option can also be specified through the
    environment variable IPYTHONDIR.
--config=<Unicode> (BaseIPythonApplication.extra_config_file)
    Default: ''
    Path to an extra config file to load.
    If specified, load this config file in addition to any other IPython config.

To see all available configurables, use `--help-all`

Examples
--------

    ipcluster nbextension enable
    ipcluster nbextension disable

[IPClusterNBExtension] CRITICAL | Bad config encountered during initialization:
[IPClusterNBExtension] CRITICAL | Unrecognized flag: '--user'
```

**Comment by hainm** [comment]
uhm, how's about
```bash
jupyter serverextension enable --py ipyparallel --user
jupyter nbextension install --py ipyparallel --user 
jupyter nbextension enable --py ipyparallel --user
```

I just tried and worked for me.

**Comment by znmeb** [comment]
Yep - that does it! Thanks!

**Comment by francisco-dlp** [comment]
I experienced the same issue today and I managed to enable the ipcluster extension using @hainm instructions above. Was this issue closed because it has been addressed somewhere in the code? If not, it would be nice if these instructions were incorporated into the error message and, even better, if the more straightforward syntax to enable the extension suggested by @hainm `ipcluster nbextension enable --user` could be implemented.

**Comment by znmeb** [comment]
@francisco-dlp I closed it because the fix worked. I consider this a documentation issue, not code. I'm not a Python programmer so I don't know the ecosystem. I did a few searches for a fix and found no usable documentation for non-Python people, so I opened this issue. I guess I could do a pull request to fix the README with the correct documentation. ;-)

**Comment by francisco-dlp** [comment]
Thank you @znmeb. I have tried adding the --user flag in #173.

**Comment by juliarm** [comment]
Thank you @hainm, this worked for me.

**Comment by exowanderer** [comment]
Hello. I have followed every instruction on here, and several others from other pages; but the clusters tab is still blank.

**Comment by ananay22** [comment]
> uhm, how's about
> 
> ```shell
> jupyter serverextension enable --py ipyparallel --user
> jupyter nbextension install --py ipyparallel --user 
> jupyter nbextension enable --py ipyparallel --user
> ```
> 
> I just tried and worked for me.

THIS WORKS!!!!
