### ISSUE TITLE
Bool object has no attribute tag

### ISSUE THREAD

**Issue by thomasklau** [ipython/ipyparallel#251]
[thomklau@gpu-9-6 ~]$ ipcluster
Traceback (most recent call last):
  File "/home/thomklau/.local/bin/ipcluster", line 7, in <module>
    from ipyparallel.apps.ipclusterapp import launch_new_instance
  File "/home/thomklau/.local/lib/python2.7/site-packages/ipyparallel/apps/ipclusterapp.py", line 573, in <module>
    class IPClusterNBExtension(BaseIPythonApplication):
  File "/home/thomklau/.local/lib/python2.7/site-packages/ipyparallel/apps/ipclusterapp.py", line 592, in IPClusterNBExtension
    user = Bool(False, help="Apply the operation only for the given user").tag(
AttributeError: 'Bool' object has no attribute 'tag'

**Comment by thomasklau** [comment]
I installed ipcluster via pip

**Comment by minrk** [comment]
Try:

    pip install --upgrade traitlets

Looks like traitlets >= 4.1 is required, but this isn't expressed explicitly in the dependencies.
