### ISSUE TITLE
Running python with -OO breaks ipyparallel import

### ISSUE THREAD

**Issue by georgedeath** [ipython/ipyparallel#261]
Importing ipyparallel when using the -O optimisation along with docstring removal (-OO) flag with Python 3.6.1 results in the following error:

```
C:\>python -OO -c "import ipyparallel"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Anaconda3\lib\site-packages\ipyparallel\__init__.py", line 17, in <module>
    from .serialize import *
  File "C:\Anaconda3\lib\site-packages\ipyparallel\serialize\__init__.py", line5, in <module>
    from .serialize import (
  File "C:\Anaconda3\lib\site-packages\ipyparallel\serialize\serialize.py", line 26, in <module>
    from jupyter_client.session import MAX_ITEMS, MAX_BYTES
  File "C:\Anaconda3\lib\site-packages\jupyter_client\__init__.py", line 8, in <module>
    from .blocking import BlockingKernelClient
  File "C:\Anaconda3\lib\site-packages\jupyter_client\blocking\__init__.py", line 1, in <module>
    from .client import BlockingKernelClient
  File "C:\Anaconda3\lib\site-packages\jupyter_client\blocking\client.py", line72, in <module>
    class BlockingKernelClient(KernelClient):
  File "C:\Anaconda3\lib\site-packages\jupyter_client\blocking\client.py", line152, in BlockingKernelClient
    execute = reqrep(KernelClient.execute)
  File "C:\Anaconda3\lib\site-packages\jupyter_client\blocking\client.py", line49, in reqrep
    basedoc, _ = meth.__doc__.split('Returns\n', 1)
AttributeError: 'NoneType' object has no attribute 'split'
```

Whereas just using the optimisation flag works fine:
```
C:\>python -O -c "import ipyparallel"
C:\>

```

System info:
```
{'commit_hash': '51ce9d73b',
 'commit_source': 'installation',
 'default_encoding': 'utf-8',
 'ipython_path': 'C:\\Anaconda3\\lib\\site-packages\\IPython',
 'ipython_version': '6.0.0',
 'os_name': 'nt',
 'platform': 'Windows-7-6.1.7601-SP1',
 'sys_executable': 'C:\\Anaconda3\\python.exe',
 'sys_platform': 'win32',
 'sys_version': '3.6.1 |Anaconda custom (64-bit)| (default, Mar 22 2017, '
                '20:11:04) [MSC v.1900 64 bit (AMD64)]'}
```

**Comment by minrk** [comment]
Indeed. Should be fixed by https://github.com/jupyter/jupyter_client/pull/254
