### ISSUE TITLE
ipcluster and ipcontrol exits

### ISSUE THREAD

**Issue by Yoonsen** [ipython/ipyparallel#271]
ipcontrol exits after failing to write to ipcontroller pid.  Current version is 6.0.2, which shows the same behaviour as previous installed version 4.1.2. The routines have worked flawlessly for about half a year before ipcluster/ipcontrol suddenly couldn't start. ipyparallel runs with Anaconde on a 20GB disk with 12GB free space.

The macine is a non networked machine.

Here is the output from ipcontrol:

[larsj@sprakbank3 ~]$ ipcontroller
2017-06-17 01:07:13.686 [IPControllerApp] Hub listening on tcp://127.0.0.1:52953 for registration.
2017-06-17 01:07:13.693 [IPControllerApp] Hub using DB backend: 'DictDB'
2017-06-17 01:07:13.953 [IPControllerApp] hub::created hub
2017-06-17 01:07:13.953 [IPControllerApp] writing connection info to /home/larsj/.ipython/profile_default/security/ipcontroller-client.json
2017-06-17 01:07:13.955 [IPControllerApp] writing connection info to /home/larsj/.ipython/profile_default/security/ipcontroller-engine.json
2017-06-17 01:07:13.956 [IPControllerApp] task::using Python leastload Task scheduler
2017-06-17 01:07:13.957 [IPControllerApp] Heartmonitor started
Traceback (most recent call last):
  File "/home/larsj/anaconda3/lib/python3.5/site-packages/ipyparallel/apps/baseapp.py", line 230, in get_pid_from_file
    pid = int(s)
ValueError: invalid literal for int() with base 10: ''

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/larsj/anaconda3/bin/ipcontroller", line 6, in <module>
    sys.exit(ipyparallel.apps.ipcontrollerapp.launch_new_instance())
  File "/home/larsj/anaconda3/lib/python3.5/site-packages/ipyparallel/apps/ipcontrollerapp.py", line 544, in launch_new_instance
    return IPControllerApp.launch_instance(*args, **kwargs)
  File "/home/larsj/anaconda3/lib/python3.5/site-packages/traitlets/config/application.py", line 596, in launch_instance
    app.start()
  File "/home/larsj/anaconda3/lib/python3.5/site-packages/ipyparallel/apps/ipcontrollerapp.py", line 518, in start
    self.write_pid_file(overwrite=True)
  File "/home/larsj/anaconda3/lib/python3.5/site-packages/ipyparallel/apps/baseapp.py", line 195, in write_pid_file
    pid = self.get_pid_from_file()
  File "/home/larsj/anaconda3/lib/python3.5/site-packages/ipyparallel/apps/baseapp.py", line 232, in get_pid_from_file
    raise PIDFileError("invalid pid file: %s (contents: %r)"%(pid_file, s))
ipyparallel.apps.baseapp.PIDFileError: invalid pid file: /home/larsj/.ipython/profile_default/pid/ipcontroller.pid (contents: '')

If you suspect this is an IPython bug, please report it at:
    https://github.com/ipython/ipython/issues
or send an email to the mailing list at ipython-dev@scipy.org

You can print a more detailed traceback right now with "%tb", or use "%debug"
to interactively debug it.

Extra-detailed tracebacks for bug-reporting purposes can be enabled via:
    c.Application.verbose_crash=True

[larsj@sprakbank3 ~]$

**Comment by Yoonsen** [comment]
Reinstalled Anaconda, and now ipcluster will start.

**Comment by Yoonsen** [comment]
Reopens this issue with a question. 

Now ipcluster starts, while clients can't connect to engines. ipcontroller still can't write to the pid file. 

In the pid file I just arbitrary put in the number 450, and now ipcontroller starts without problems, as well as ipcluster. Moreover, clients can connect and everything seems to work.

So, question - will anything bad happen if I just manually put in a number in the pid file?

Best,
Lars
