### ISSUE TITLE
How to debug/exceptions in parallel code?

### ISSUE THREAD

**Issue by floli** [ipython/ipyparallel#291]
Hello,

given that code:

```
import ipyparallel
rc = ipyparallel.Client()
dview = rc[:]
dview.use_cloudpickle()
lview = rc.load_balanced_view()
lview.block = True

def fun():
    raise Exception('foobar')

@lview.parallel()
def kernel(size):
    fun()
    return size * size

kernel.map([1,2,3])
```

gives me that traceback:

```
Traceback (most recent call last):
  File "ipyparallel-debug.py", line 16, in <module>
    kernel.map([1,2,3])
  File "/usr/lib/python3.6/site-packages/ipyparallel/client/remotefunction.py", line 285, in map
    return self(*sequences, __ipp_mapping=True)
  File "<decorator-gen-118>", line 2, in __call__
  File "/usr/lib/python3.6/site-packages/ipyparallel/client/remotefunction.py", line 79, in sync_view_results
    ret = f(self, *args, **kwargs)
  File "/usr/lib/python3.6/site-packages/ipyparallel/client/remotefunction.py", line 271, in __call__
    return r.get()
  File "/usr/lib/python3.6/site-packages/ipyparallel/client/asyncresult.py", line 167, in get
    raise self.exception()
  File "/usr/lib/python3.6/site-packages/ipyparallel/client/asyncresult.py", line 226, in _resolve_result
    results = error.collect_exceptions(results, self._fname)
  File "/usr/lib/python3.6/site-packages/ipyparallel/error.py", line 233, in collect_exceptions
    raise e
  File "/usr/lib/python3.6/site-packages/ipyparallel/error.py", line 231, in collect_exceptions
    raise CompositeError(msg, elist)
ipyparallel.error.CompositeError: one or more exceptions from call to method: kernel
[1:apply]: Exception: foobar
[0:apply]: Exception: foobar
[1:apply]: Exception: foobar
```

which is not very helpful to find the place where the exception was thrown and to debug it. Right now, I often remote the decorator and the kernel.map, replace it by a list comprehension and run it again, just to get a helpful traceback.

How to improve that?

* Can I somehow print the entire exception from the paralllel code?
* Can I somehow _disable_ ipyparallel, so that it just runs in serial on the local host, but allows debugging and prints proper exceptions?

**Comment by minrk** [comment]
Hi! I’m going through and cleaning up old/stale issues on this repo. Sorry for not responding in a reasonable amount of time!


I’m especially closing old “how to” or debugging questions to keep the Issues list to bug reports and feature requests. These can be directed to [the Jupyter forum](http://discourse.jupyter.org) if still relevant.

> Can I somehow print the entire exception from the paralllel code?

`CompositeError.print_traceback()` will show you the full remote tracebacks, if you are interested.

> Can I somehow disable ipyparallel

ipyparallel uses `map`-style APIs specifically because they also exist in the standard library, and are compatible. Using the decorated-functions approach is less portable, but if you did, say:

```python
for item in lview.map(kernel, [1, 2, 3]):
    # remote
```

you can do the exact same thing with the builtin `map`:

```python
for item in map(kernel, [1, 2, 3]):
    # local
```

without invoking ipython parallel.
