### ISSUE TITLE
pyzmq >= 17 make ipyparallel unstable

### ISSUE THREAD

**Issue by cyberwillis** [ipython/ipyparallel#303]
I just got many issues last week when I had to reinstall ubuntu in my machine and the packages again.
My previous projects and code just stopped to work, as normally and sometimes just hanged or other times made my kernel in jupyter just get restarted.
I just found out that my problem was pyzmq 17.0.0b3 in my system causing many many troubles.
That drove me crazy for a couple days because my code was working nicely before.
Now that i get the last stable version everything is smooth again.

**Comment by minrk** [comment]
The pyzmq eventloop integration in 17.0 is totally changed and relies on zmq's edge-triggered FDs. Can you share `pip list`? Since you have prerelease pyzmq, do you also have tornado 5.0a1?

**Comment by cyberwillis** [comment]
https://github.com/zeromq/pyzmq/issues/1120#issuecomment-352750309

**Comment by cyberwillis** [comment]
The problem with pyzqm continues.

https://github.com/zeromq/pyzmq/issues/1120#issuecomment-352750309

I just find out another problem.

Even if using pyzmq==16.04 the stable version that works for me, in case I change the tornado to alpha version (tornado==5.0a1) I cant start ipcluster anymore.


```
> ipcontroller --ip=* --profile='default'2018-01-26 21:18:20.129 [IPControllerApp] ERROR | Couldn't construct the Controller
Traceback (most recent call last):  File "/usr/local/lib/python3.5/dist-packages/traitlets/traitlets.py", line 528, in get
    value = obj._trait_values[self.name]KeyError: 'loop'
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/ipyparallel/apps/ipcontrollerapp.py", line 328, in init_hub
    self.factory.init_hub()  File "/usr/local/lib/python3.5/dist-packages/ipyparallel/controller/hub.py", line 255, in init_hub    loop = self.loop
  File "/usr/local/lib/python3.5/dist-packages/traitlets/traitlets.py", line 556, in __get__    return self.get(obj, cls)
  File "/usr/local/lib/python3.5/dist-packages/traitlets/traitlets.py", line 535, in get    value = self._validate(obj, dynamic_default())
  File "/usr/local/lib/python3.5/dist-packages/jupyter_client/session.py", line 196, in _loop_default
    return IOLoop.current()  File "/home/willismar/.local/lib/python3.5/site-packages/zmq/eventloop/ioloop.py", line 167, in current    PollIOLoop.configure(cls)
  File "/home/willismar/.local/lib/python3.5/site-packages/tornado/ioloop.py", line 195, in configure
    "only AsyncIOLoop is allowed when asyncio is available")RuntimeError: only AsyncIOLoop is allowed when asyncio is available
```

**Comment by cyberwillis** [comment]
Hi again, 

I build ipyparallel from the source now with merged code,  and when I tried to run:

ipcluster start --ip=* -n 8

I got this error:

```
2018-01-31 14:59:38.167 [IPClusterStart] Starting ipcluster with [daemon=False]
2018-01-31 14:59:38.167 [IPClusterStart] Creating pid file: /home/willismar/.ipython/profile_default/pid/ipcluster.pid
2018-01-31 14:59:38.168 [IPClusterStart] Starting Controller with LocalControllerLauncher
2018-01-31 14:59:38.171 [IPClusterStart] ERROR | Controller start failed
Traceback (most recent call last):
  File "/home/willismar/.local/lib/python3.5/site-packages/ipyparallel/apps/ipclusterapp.py", line 526, in start_controller
    self.controller_launcher.start()
  File "/home/willismar/.local/lib/python3.5/site-packages/ipyparallel/apps/launcher.py", line 340, in start
    return super(LocalControllerLauncher, self).start()
  File "/home/willismar/.local/lib/python3.5/site-packages/ipyparallel/apps/launcher.py", line 272, in start
    self.poller = ioloop.PeriodicCallback(self.poll, self.poll_frequency, self.loop)
TypeError: __init__() takes 3 positional arguments but 4 were given
ERROR:tornado.application:Exception in callback functools.partial(<function wrap.<locals>.null_wrapper at 0x7f574e8e1048>)
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/tornado/ioloop.py", line 749, in _run_callback
    ret = callback()
  File "/usr/local/lib/python3.5/dist-packages/tornado/stack_context.py", line 277, in null_wrapper
    return fn(*args, **kwargs)
  File "/home/willismar/.local/lib/python3.5/site-packages/ipyparallel/apps/ipclusterapp.py", line 571, in start
    self.start_controller()
  File "/home/willismar/.local/lib/python3.5/site-packages/ipyparallel/apps/ipclusterapp.py", line 526, in start_controller
    self.controller_launcher.start()
  File "/home/willismar/.local/lib/python3.5/site-packages/ipyparallel/apps/launcher.py", line 340, in start
    return super(LocalControllerLauncher, self).start()
  File "/home/willismar/.local/lib/python3.5/site-packages/ipyparallel/apps/launcher.py", line 272, in start
    self.poller = ioloop.PeriodicCallback(self.poll, self.poll_frequency, self.loop)
TypeError: __init__() takes 3 positional arguments but 4 were given
```

Here are the packages I have installed. 
```
bleach==2.1.2
certifi==2018.1.18
chardet==3.0.4
decorator==4.2.1
entrypoints==0.2.3
h5py==2.7.0
html5lib==1.0.1
idna==2.6
ipykernel==4.8.0
ipyparallel==6.1.0.dev0
ipython==6.2.1
ipython-genutils==0.2.0
ipywidgets==7.1.1
jedi==0.11.1
Jinja2==2.10
joblib==0.11
jsonschema==2.6.0
jupyter-client==5.2.1
jupyter-contrib-core==0.3.3
jupyter-contrib-nbextensions==0.3.3
jupyter-core==4.4.0
jupyter-highlight-selected-word==0.1.0
jupyter-latex-envs==1.4.1
jupyter-nbextensions-configurator==0.4.0
jupyterlab==0.30.6
jupyterlab-launcher==0.6.0
lxml==4.1.1
MarkupSafe==1.0
mistune==0.8.3
mpi4py==3.0.0
nbconvert==5.3.1
nbformat==4.4.0
notebook==5.3.1
numpy==1.14.0
pandocfilters==1.4.2
parso==0.1.1
pexpect==4.3.1
pickleshare==0.7.4
Pillow==5.0.0
prompt-toolkit==1.0.15
ptyprocess==0.5.2
Pygments==2.2.0
python-dateutil==2.6.1
PyYAML==3.12
pyzmq==17.0.0b4
requests==2.18.4
scipy==1.0.0
Send2Trash==1.4.2
simplegeneric==0.8.1
six==1.11.0
terminado==0.8.1
testpath==0.3.1
tornado==5.0a1
tqdm==4.19.5
traitlets==4.3.2
urllib3==1.22
wcwidth==0.1.7
webencodings==0.5.1
widgetsnbextension==3.1.3
xlrd==1.1.0
```

**BTW if I use tornado 4.5.3 this error does not happen in the initialization and everything continues to work.**

**Comment by cyberwillis** [comment]
Let me correct my last post here...
Tornado just released a new version tornado==5.0b1 and now with pyzmq==17.0.0b4 and the lastest merged source it worked for ( ipcluster -n 8 ).
However I findout if I use ipcontroller --ip="*" --profile='default' now the 
ipcontroller-engine.json has a property location pointng to a hashcode instead of the IP previously.

So I couldn't make sure it will work in a distributed LAN

**Comment by cyberwillis** [comment]
Never mind...

I solved the IP problem using this post :   https://github.com/ipython/ipyparallel/pull/252

And I can confirm it works using 
tornado==5.0b1
pyzmq==17.0.0b4
ipyparallel==6.1.0.dev0

For ipcluster or ipyparallel

**Comment by freedomtowin** [comment]
Hello @cyberwillis,  

Does the solution you referenced work for python>=3.6?

The newer distributions of tornado and pyzmq appear to use hyperthreading in addition to multi-processing. For some reason, the parallel processing is very slow with these distributions.

**Comment by cyberwillis** [comment]
hi @freedomtowin 

Take a look on this post of mine... 
If you can run that simple code it must work for you. https://github.com/zeromq/pyzmq/issues/1120#issuecomment-360928797

**Comment by cyberwillis** [comment]
I work in containers now to not have much trouble with package versions. I just build a container with versions bellow and I didn't saw any problem:

**python --version**
```
Python 3.6.9 :: Anaconda, Inc.
```


**pip freeze**:
```
ipyparallel==6.2.4
pyzmq==18.1.0 
tornado==6.0.3
```
