### ISSUE TITLE
MemoryError with Tornado Exception

### ISSUE THREAD

**Issue by cc9hwa** [ipython/ipyparallel#305]
Hi,

I am paralleling grid search of RandomForestClassifier using HPC 2012 + ipyparallel5.2 on Python 3.4(Anaconda3) and eventually (after few hours runs) got the following errors in log\ipcontroller.err.

Can you please advise.

Thanks

--------------------------------------------------------------------------------------------------------------

ERROR:tornado.general:Uncaught exception, closing connection.
Traceback (most recent call last):
  File "C:\Anaconda3\lib\site-packages\zmq\eventloop\zmqstream.py", line 433, in _handle_events
    self._handle_recv()
  File "C:\Anaconda3\lib\site-packages\zmq\eventloop\zmqstream.py", line 454, in _handle_recv
    msg = self.socket.recv_multipart(zmq.NOBLOCK, copy=self._recv_copy)
  File "C:\Anaconda3\lib\site-packages\zmq\sugar\socket.py", line 361, in recv_multipart
    part = self.recv(flags, copy=copy, track=track)
  File "zmq/backend/cython/socket.pyx", line 676, in zmq.backend.cython.socket.Socket.recv (zmq\backend\cython\socket.c:6507)
  File "zmq/backend/cython/socket.pyx", line 710, in zmq.backend.cython.socket.Socket.recv (zmq\backend\cython\socket.c:6307)
  File "zmq/backend/cython/socket.pyx", line 152, in zmq.backend.cython.socket._recv_copy (zmq\backend\cython\socket.c:1955)
  File "zmq/backend/cython/message.pxd", line 61, in zmq.backend.cython.message.copy_zmq_msg_bytes (zmq\backend\cython\socket.c:7148)
MemoryError
ERROR:tornado.application:Exception in callback None
Traceback (most recent call last):
  File "C:\Anaconda3\lib\site-packages\tornado\ioloop.py", line 866, in start
    handler_func(fd_obj, events)
  File "C:\Anaconda3\lib\site-packages\tornado\stack_context.py", line 275, in null_wrapper
    return fn(*args, **kwargs)
  File "C:\Anaconda3\lib\site-packages\zmq\eventloop\zmqstream.py", line 433, in _handle_events
    self._handle_recv()
  File "C:\Anaconda3\lib\site-packages\zmq\eventloop\zmqstream.py", line 454, in _handle_recv
    msg = self.socket.recv_multipart(zmq.NOBLOCK, copy=self._recv_copy)
  File "C:\Anaconda3\lib\site-packages\zmq\sugar\socket.py", line 361, in recv_multipart
    part = self.recv(flags, copy=copy, track=track)
  File "zmq/backend/cython/socket.pyx", line 676, in zmq.backend.cython.socket.Socket.recv (zmq\backend\cython\socket.c:6507)
  File "zmq/backend/cython/socket.pyx", line 710, in zmq.backend.cython.socket.Socket.recv (zmq\backend\cython\socket.c:6307)
  File "zmq/backend/cython/socket.pyx", line 152, in zmq.backend.cython.socket._recv_copy (zmq\backend\cython\socket.c:1955)
  File "zmq/backend/cython/message.pxd", line 61, in zmq.backend.cython.message.copy_zmq_msg_bytes (zmq\backend\cython\socket.c:7148)
MemoryError

**Comment by minrk** [comment]
MemoryError means you are out of memory. You can try purging intermediate results to avoid eating up too much.
