### ISSUE TITLE
AttributeError: 'PBSControllerLauncher' object has no attribute 'controller_args'

### ISSUE THREAD

**Issue by basnijholt** [ipython/ipyparallel#311]
I've just updated to 6.1.0 and try to start an ipcluster on a PBS system.

I have the following config:
```
# ipcluster_config.py
c.IPClusterEngines.engine_launcher_class = 'PBSEngineSetLauncher'
c.IPClusterStart.controller_launcher_class = 'PBSControllerLauncher'
```

traceback:
```
hpc05 ➜  ~  ipcluster start --n=1 --profile=pbs
Traceback (most recent call last):
  File "/home/basnijholt/miniconda3/bin/ipcluster", line 11, in <module>
    sys.exit(launch_new_instance())
  File "/home/basnijholt/miniconda3/lib/python3.6/site-packages/traitlets/config/application.py", line 657, in launch_instance
    app.initialize(argv)
  File "<decorator-gen-7>", line 2, in initialize
  File "/home/basnijholt/miniconda3/lib/python3.6/site-packages/traitlets/config/application.py", line 87, in catch_config_error
    return method(app, *args, **kwargs)
  File "/home/basnijholt/miniconda3/lib/python3.6/site-packages/IPython/core/application.py", line 450, in initialize
    self.parse_command_line(argv)
  File "<decorator-gen-4>", line 2, in parse_command_line
  File "/home/basnijholt/miniconda3/lib/python3.6/site-packages/traitlets/config/application.py", line 87, in catch_config_error
    return method(app, *args, **kwargs)
  File "/home/basnijholt/miniconda3/lib/python3.6/site-packages/traitlets/config/application.py", line 514, in parse_command_line
    return self.initialize_subcommand(subc, subargv)
  File "/home/basnijholt/miniconda3/lib/python3.6/site-packages/IPython/core/application.py", line 243, in initialize_subcommand
    return super(BaseIPythonApplication, self).initialize_subcommand(subc, argv)
  File "<decorator-gen-3>", line 2, in initialize_subcommand
  File "/home/basnijholt/miniconda3/lib/python3.6/site-packages/traitlets/config/application.py", line 87, in catch_config_error
    return method(app, *args, **kwargs)
  File "/home/basnijholt/miniconda3/lib/python3.6/site-packages/traitlets/config/application.py", line 452, in initialize_subcommand
    self.subapp.initialize(argv)
  File "<decorator-gen-146>", line 2, in initialize
  File "/home/basnijholt/miniconda3/lib/python3.6/site-packages/traitlets/config/application.py", line 87, in catch_config_error
    return method(app, *args, **kwargs)
  File "/home/basnijholt/miniconda3/lib/python3.6/site-packages/ipyparallel/apps/ipclusterapp.py", line 305, in initialize
    self.init_launchers()
  File "/home/basnijholt/miniconda3/lib/python3.6/site-packages/ipyparallel/apps/ipclusterapp.py", line 509, in init_launchers
    controller_args = self.controller_launcher.controller_args
AttributeError: 'PBSControllerLauncher' object has no attribute 'controller_args'

If you suspect this is an IPython bug, please report it at:
    https://github.com/ipython/ipython/issues
or send an email to the mailing list at ipython-dev@python.org

You can print a more detailed traceback right now with "%tb", or use "%debug"
to interactively debug it.

Extra-detailed tracebacks for bug-reporting purposes can be enabled via:
    c.Application.verbose_crash=True

```

**Comment by minrk** [comment]
Sorry about that. Should be fixed with a band-aid by #312. If you verify that one, I can cut 6.1.1. I've opened #313 to track a more substantial fix to ensure all Launchers get the feature affected.
