### ISSUE TITLE
dview.push breaks when using dill or cloudpickle 

### ISSUE THREAD

**Issue by basnijholt** [ipython/ipyparallel#317]
```python
import ipyparallel
client = ipyparallel.Client()
dview = client[:]

dview.use_dill()

def bar(x):
    return x * x

dview.push(dict(foo=foo))
%px foo
```

traceback:
```
[0:execute]: 
---------------------------------------------------------------------------NameError                                 Traceback (most recent call last)<ipython-input-1-f1d2d2f924e9> in <module>()
----> 1 foo
NameError: name 'foo' is not defined
```

**Comment by stuartthomas25** [comment]
I'm having the same issue, Bas. Do you think this could be an issue specific to us?

**Comment by maxgillett** [comment]
I'm having the same issue. Unable to push. Also, dill 0.3.1.1 breaks ipyparallel, so I had to use version 0.3.0.

I was also not able to get cloud_pickle to work at all, as the engines complain that the module cannot be found.

**Comment by basnijholt** [comment]
@maxgillett, I am experiencing problems with dill too, did you mean that `0.3.1.1` breaks it like:
```python
Traceback (most recent call last):
  File "/gscratch/home/a-banijh/miniconda3/envs/py38/lib/python3.8/site-packages/adaptive/runner.py", line 211, in _process_futures
    y = fut.result()
  File "/gscratch/home/a-banijh/miniconda3/envs/py38/lib/python3.8/asyncio/futures.py", line 178, in result
    raise self._exception
  File "/gscratch/home/a-banijh/miniconda3/envs/py38/lib/python3.8/site-packages/ipyparallel/client/asyncresult.py", line 226, in _resolve_result
    raise r
ipyparallel.error.RemoteError: AttributeError(Can't get attribute '_create_code' on <module 'dill._dill' from '/gscratch/home/a-banijh/miniconda3/envs/py37_new/lib/python3.7/site-packages/dill/_dill.py'>)
```
