### ISSUE TITLE
ipcluster install issues with anaconda

### ISSUE THREAD

**Issue by rddaz2013** [ipython/ipyparallel#335]
with "ipcluster nbextension enable" i get this error..

```
Traceback (most recent call last):
  File "/home/rened/anaconda3/bin/ipcluster", line 11, in <module>
    sys.exit(launch_new_instance())
  File "/home/rened/anaconda3/lib/python3.6/site-packages/traitlets/config/application.py", line 658, in launch_instance
    app.start()
  File "/home/rened/anaconda3/lib/python3.6/site-packages/ipyparallel/apps/ipclusterapp.py", line 668, in start
    return self.subapp.start()
  File "/home/rened/anaconda3/lib/python3.6/site-packages/ipyparallel/apps/ipclusterapp.py", line 631, in start
    install_extensions(enable=True, user=self.user)
  File "/home/rened/anaconda3/lib/python3.6/site-packages/ipyparallel/nbextension/install.py", line 24, in install_extensions
    toggle_serverextension_python('ipyparallel.nbextension', user=user)
  File "/home/rened/anaconda3/lib/python3.6/site-packages/notebook/serverextensions.py", line 74, in toggle_serverextension_python
    cm.update("jupyter_notebook_config", cfg)
  File "/home/rened/anaconda3/lib/python3.6/site-packages/traitlets/config/manager.py", line 87, in update
    self.set(section_name, data)
  File "/home/rened/anaconda3/lib/python3.6/site-packages/traitlets/config/manager.py", line 71, in set
    self.ensure_config_dir_exists()
  File "/home/rened/anaconda3/lib/python3.6/site-packages/traitlets/config/manager.py", line 46, in ensure_config_dir_exists
    os.makedirs(self.config_dir, 0o755)
  File "/home/rened/anaconda3/lib/python3.6/os.py", line 220, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: '/usr/local/etc/jupyter'
```

**Comment by saswat01** [comment]
I too receive the same kind of error....anyone out there for help!

**Comment by rulingfong** [comment]
same issue

**Comment by rddaz2013** [comment]
#788

**Comment by twoflypig** [comment]
As #186 said:
`ipcluster nbextension enable --user`
