### ISSUE TITLE
Failed to add/update records when using MongoDB backend

### ISSUE THREAD

**Issue by dyj6146** [ipython/ipyparallel#340]
When I submit tasks to either direct or load balanced view using either map or apply_sync I see logs below:

`2018-09-18 23:27:05.936 [IPClusterStart] 2018-09-18 23:27:05.935 [IPControllerApp] ERROR | DB Error updating record u'e5925b97-b0906f91a3415ce89c3c2299'
2018-09-18 23:27:05.936 [IPClusterStart] Traceback (most recent call last):
2018-09-18 23:27:05.937 [IPClusterStart]   File "/home/ifu/anaconda2/lib/python2.7/site-packages/ipyparallel/controller/hub.py", line 693, in save_queue_result
2018-09-18 23:27:05.937 [IPClusterStart]     self.db.update_record(msg_id, result)
2018-09-18 23:27:05.937 [IPClusterStart]   File "/home/ifu/anaconda2/lib/python2.7/site-packages/ipyparallel/controller/mongodb.py", line 87, in update_record
2018-09-18 23:27:05.937 [IPClusterStart]     rec = self._binary_buffers(rec)
2018-09-18 23:27:05.937 [IPClusterStart]   File "/home/ifu/anaconda2/lib/python2.7/site-packages/ipyparallel/controller/mongodb.py", line 68, in _binary_buffers
2018-09-18 23:27:05.937 [IPClusterStart]     rec[key] = list(map(Binary, rec[key]))
2018-09-18 23:27:05.937 [IPClusterStart]   File "/home/ifu/anaconda2/lib/python2.7/site-packages/bson/binary.py", line 147, in __new__
2018-09-18 23:27:05.937 [IPClusterStart]     raise TypeError("data must be an instance of bytes")
2018-09-18 23:27:05.937 [IPClusterStart] TypeError: data must be an instance of bytes`

Looks like key['buffers'] cannot be binarized?

**Comment by minrk** [comment]
Looks like you're right that pymongo doesn't support the Python buffer interface and we should be casting memoryviews to bytes.
