### ISSUE TITLE
Stop execution using signal.alarm and printing out debug messages from individual engines

### ISSUE THREAD

**Issue by anirban6908** [ipython/ipyparallel#354]
Hi,
I am using ipyparallel to run optimization jobs using deap. On each of the engines I run the method evaluate_with_dicts

```
import logging
logger = logging.getLogger(__name__)

import bluepyopt as bpopt
import bluepyopt.tools

import signal
import time

class TimeoutException(Exception):   # Custom exception class
    pass

def timeout_handler(signum, frame):   # Custom signal handler
    raise TimeoutException



class CellEvaluatorTimed(CellEvaluator):

    """Timed evaluation cell class"""
    def __init__(self, **kwargs):
        super(CellEvaluatorTimed, self).__init__(**kwargs)

    def evaluate_with_dicts(self, param_dict=None):
        """Run evaluation with dict as input and output"""
		
	## Change the behavior of SIGALRM
	signal.signal(signal.SIGALRM, timeout_handler)

        logger.debug('Evaluating %s', self.cell_model.name)

        responses = {}
        
        for protocol in self.fitness_protocols.values():
            signal.alarm(5*60)
            try:
            start_time = time.time()
            results = self.run_protocol(
                protocol,
                param_values=param_dict,
                isolate=self.isolate_protocols)
            responses.update(results)
            
            except TimeoutException:
                logger.debug('Simulation missed 5 min cut-off for protocol %s'%protocol.name)
                continue
            else:
                # Reset the alarm
                signal.alarm(0)
                
            end_time = time.time()
            sim_dur = end_time - start_time
            logger.debug('Simulation took %s seconds', %sim_dur)
            
        return self.fitness_calculator.calculate_scores(responses)

```

Within the for loop in that method I run the simulations serially and I want the simulations to stop when it exceeds a certain time using signal.alarm. So let's say for 5 simulations if only 3 simulations pass the cut off time of 5 mins the returned dictionary responses will have 3 key, value pairs only. I have tried this on both my machine and on the cluster, but I don't think this is working, also without printing the debug statements especially from the try except block, it's hard to understand whether it catches the signals or not. Would greatly appreciate any help.
Thanks

**Comment by minrk** [comment]
Hi! I’m going through and cleaning up old/stale issues on this repo. Sorry for not responding in a reasonable amount of time!

I’m especially closing old “how to” or debugging questions to keep the Issues list to bug reports and feature requests. These can be directed to [the Jupyter forum](http://discourse.jupyter.org) if still relevant.

Two answers to your questions:

1. `signal.alarm` does work in general, so it might be something peculiar to your code where SIGALRM is not firing or the signal handler is being overridden.
2. if you set up a logger hooked up to sys.stdout, you can get those logs by accessing `AsyncResult.stdout`.

This example captures the debug logging and exits on alarm:

```python
import logging

from ipyparallel import Client


def setup_logging(level=logging.DEBUG):
    import logging
    import sys

    logger = logging.getLogger("task")
    logger.setLevel(level)
    if not logger.handlers:
        logger.addHandler(logging.StreamHandler(sys.stdout))


def task():
    import logging, signal, time

    logger = logging.getLogger("task")

    def timeout_handler(sig, frame):
        logger.debug("Alarm time!")
        raise RuntimeError("Alarm!")

    logger.debug("Registering signal handler")
    signal.signal(signal.SIGALRM, timeout_handler)
    signal.alarm(1)
    logger.debug("Sleeping")
    time.sleep(5)

client = Client()
view = client[:]
view.apply_sync(setup_logging, level=logging.DEBUG)
ar = view.apply_async(task)
ar.wait_interactive()
ar.wait_for_output()

# print stdout for each engine
for eid, stdout in zip(ar.engine_id, ar.stdout):
    print(f"[stdout {eid}] {stdout}")

# print results (will raise if there was an error)
print("results", ar.get())
```

which produces the output:

```
   4/4 tasks finished after    1 s
done
[stdout 0] Registering signal handler
Sleeping
Alarm time!

[stdout 1] Registering signal handler
Sleeping
Alarm time!

[stdout 2] Registering signal handler
Sleeping
Alarm time!

[stdout 3] Registering signal handler
Sleeping
Alarm time!

Traceback (most recent call last):
  File "test.py", line 42, in <module>
    print("results", ar.get())
  File "/Users/minrk/dev/ip/parallel/ipyparallel/client/asyncresult.py", line 223, in get
    raise self.exception()
  File "/Users/minrk/dev/ip/parallel/ipyparallel/client/asyncresult.py", line 282, in _resolve_result
    results = error.collect_exceptions(results, self._fname)
  File "/Users/minrk/dev/ip/parallel/ipyparallel/error.py", line 243, in collect_exceptions
    raise e
  File "/Users/minrk/dev/ip/parallel/ipyparallel/error.py", line 241, in collect_exceptions
    raise CompositeError(msg, elist)
ipyparallel.error.CompositeError: one or more exceptions from call to method: task
[0:apply]: RuntimeError: Alarm!
[1:apply]: RuntimeError: Alarm!
[2:apply]: RuntimeError: Alarm!
[3:apply]: RuntimeError: Alarm!
```
