### ISSUE TITLE
Permission denied on selected random port

### ISSUE THREAD

**Issue by zyndagj** [ipython/ipyparallel#355]
Hello,

I have been encountering the  `ZMQError: Permission denied` error on my system when attempting to start an ipcluster.

```
(ipyrad) nid00657(1001)$ ipcluster start -n 1 --debug

2019-02-18 11:21:09.266 [IPClusterStart] IPYTHONDIR set to: /home1/03076/gzynda/.ipython
2019-02-18 11:21:09.269 [IPClusterStart] Using existing profile dir: u'/home1/03076/gzynda/.ipython/profile_default'
2019-02-18 11:21:09.269 [IPClusterStart] Searching path [u'/scratch/03076/gzynda/consulting/ipyrad', u'/home1/03076/gzynda/.ipython/profile_default', '/home1/03076/gzynda/apps/python/conda2.7/envs/ipyrad/etc/ipython', '/usr/local/etc/ipython', '/etc/ipython'] for config files
2019-02-18 11:21:09.269 [IPClusterStart] Attempting to load config file: ipython_config.py
2019-02-18 11:21:09.269 [IPClusterStart] Looking for ipython_config in /etc/ipython
2019-02-18 11:21:09.270 [IPClusterStart] Looking for ipython_config in /usr/local/etc/ipython
2019-02-18 11:21:09.270 [IPClusterStart] Looking for ipython_config in /home1/03076/gzynda/apps/python/conda2.7/envs/ipyrad/etc/ipython
2019-02-18 11:21:09.270 [IPClusterStart] Looking for ipython_config in /home1/03076/gzynda/.ipython/profile_default
2019-02-18 11:21:09.270 [IPClusterStart] Looking for ipython_config in /scratch/03076/gzynda/consulting/ipyrad
2019-02-18 11:21:09.271 [IPClusterStart] Attempting to load config file: ipcluster_config.py
2019-02-18 11:21:09.272 [IPClusterStart] Looking for ipcontroller_config in /etc/ipython
2019-02-18 11:21:09.272 [IPClusterStart] Looking for ipcontroller_config in /usr/local/etc/ipython
2019-02-18 11:21:09.272 [IPClusterStart] Looking for ipcontroller_config in /home1/03076/gzynda/apps/python/conda2.7/envs/ipyrad/etc/ipython
2019-02-18 11:21:09.272 [IPClusterStart] Looking for ipcontroller_config in /home1/03076/gzynda/.ipython/profile_default
2019-02-18 11:21:09.272 [IPClusterStart] Looking for ipcontroller_config in /scratch/03076/gzynda/consulting/ipyrad
2019-02-18 11:21:09.273 [IPClusterStart] Attempting to load config file: ipcluster_config.py
2019-02-18 11:21:09.273 [IPClusterStart] Looking for ipengine_config in /etc/ipython
2019-02-18 11:21:09.273 [IPClusterStart] Looking for ipengine_config in /usr/local/etc/ipython
2019-02-18 11:21:09.273 [IPClusterStart] Looking for ipengine_config in /home1/03076/gzynda/apps/python/conda2.7/envs/ipyrad/etc/ipython
2019-02-18 11:21:09.273 [IPClusterStart] Looking for ipengine_config in /home1/03076/gzynda/.ipython/profile_default
2019-02-18 11:21:09.273 [IPClusterStart] Looking for ipengine_config in /scratch/03076/gzynda/consulting/ipyrad
2019-02-18 11:21:09.274 [IPClusterStart] Attempting to load config file: ipcluster_config.py
2019-02-18 11:21:09.274 [IPClusterStart] Looking for ipcluster_config in /etc/ipython
2019-02-18 11:21:09.274 [IPClusterStart] Looking for ipcluster_config in /usr/local/etc/ipython
2019-02-18 11:21:09.275 [IPClusterStart] Looking for ipcluster_config in /home1/03076/gzynda/apps/python/conda2.7/envs/ipyrad/etc/ipython
2019-02-18 11:21:09.275 [IPClusterStart] Looking for ipcluster_config in /home1/03076/gzynda/.ipython/profile_default
2019-02-18 11:21:09.275 [IPClusterStart] Looking for ipcluster_config in /scratch/03076/gzynda/consulting/ipyrad
2019-02-18 11:21:09.279 [IPClusterStart] Starting ipcluster with [daemon=False]
2019-02-18 11:21:09.280 [IPClusterStart] Creating pid file: /home1/03076/gzynda/.ipython/profile_default/pid/ipcluster.pid
2019-02-18 11:21:09.280 [IPClusterStart] Starting Controller with LocalControllerLauncher
2019-02-18 11:21:09.281 [IPClusterStart] Starting LocalControllerLauncher: ['/home1/03076/gzynda/apps/python/conda2.7/envs/ipyrad/bin/python', '-m', 'ipyparallel.controller', '--profile-dir', u'/home1/03076/gzynda/.ipython/profile_default', '--cluster-id', u'', '--log-level=20']
2019-02-18 11:21:09.283 [IPClusterStart] Process '/home1/03076/gzynda/apps/python/conda2.7/envs/ipyrad/bin/python' started: 39348
2019-02-18 11:21:10.284 [IPClusterStart] Starting 1 Engines with LocalEngineSetLauncher
2019-02-18 11:21:10.285 [IPClusterStart] Starting LocalEngineLauncher: ['/home1/03076/gzynda/apps/python/conda2.7/envs/ipyrad/bin/python', '-m', 'ipyparallel.engine', '--profile-dir', u'/home1/03076/gzynda/.ipython/profile_default', '--cluster-id', u'', '--log-level=20']
2019-02-18 11:21:10.288 [IPClusterStart] Process '/home1/03076/gzynda/apps/python/conda2.7/envs/ipyrad/bin/python' started: 39353
2019-02-18 11:21:10.288 [IPClusterStart] Process 'engine set' started: [None]
2019-02-18 11:21:10.565 [IPClusterStart] 2019-02-18 11:21:10.565 [IPControllerApp] Using existing profile dir: u'/home1/03076/gzynda/.ipython/profile_default'
2019-02-18 11:21:10.578 [IPClusterStart] 2019-02-18 11:21:10.578 [IPControllerApp] Binding to tcp://127.0.0.1:26
2019-02-18 11:21:10.583 [IPClusterStart] 2019-02-18 11:21:10.579 [IPControllerApp] ERROR | Couldn't construct the Controller
2019-02-18 11:21:10.583 [IPClusterStart] Traceback (most recent call last):
2019-02-18 11:21:10.583 [IPClusterStart]   File "/home1/03076/gzynda/apps/python/conda2.7/envs/ipyrad/lib/python2.7/site-packages/ipyparallel/apps/ipcontrollerapp.py", line 301, in init_hub
2019-02-18 11:21:10.583 [IPClusterStart]     self.factory.init_hub()
2019-02-18 11:21:10.583 [IPClusterStart]   File "/home1/03076/gzynda/apps/python/conda2.7/envs/ipyrad/lib/python2.7/site-packages/ipyparallel/controller/hub.py", line 292, in init_hub
2019-02-18 11:21:10.583 [IPClusterStart]     q.bind(self.client_url('registration'))
2019-02-18 11:21:10.583 [IPClusterStart]   File "zmq/backend/cython/socket.pyx", line 547, in zmq.backend.cython.socket.Socket.bind
2019-02-18 11:21:10.583 [IPClusterStart]   File "zmq/backend/cython/checkrc.pxd", line 25, in zmq.backend.cython.checkrc._check_rc
2019-02-18 11:21:10.583 [IPClusterStart]     raise ZMQError(errno)
2019-02-18 11:21:10.583 [IPClusterStart] ZMQError: Permission denied
2019-02-18 11:21:10.610 [IPClusterStart] Process '/home1/03076/gzynda/apps/python/conda2.7/envs/ipyrad/bin/python' stopped: {'pid': 39348, 'exit_code': 1}
2019-02-18 11:21:10.610 [IPClusterStart] ERROR | IPython cluster: stopping
2019-02-18 11:21:10.610 [IPClusterStart] Stopping Engines...
2019-02-18 11:21:10.610 [IPClusterStart] Traceback (most recent call last):
2019-02-18 11:21:10.611 [IPClusterStart]   File "/home1/03076/gzynda/apps/python/conda2.7/envs/ipyrad/lib/python2.7/runpy.py", line 163, in _run_module_as_main
2019-02-18 11:21:10.611 [IPClusterStart]     mod_name, _Error)
2019-02-18 11:21:10.611 [IPClusterStart]   File "/home1/03076/gzynda/apps/python/conda2.7/envs/ipyrad/lib/python2.7/runpy.py", line 102, in _get_module_details
2019-02-18 11:21:10.611 [IPClusterStart]     loader = get_loader(mod_name)
2019-02-18 11:21:10.612 [IPClusterStart]   File "/home1/03076/gzynda/apps/python/conda2.7/envs/ipyrad/lib/python2.7/pkgutil.py", line 462, in get_loader
2019-02-18 11:21:10.612 [IPClusterStart]     return find_loader(fullname)
2019-02-18 11:21:10.612 [IPClusterStart]   File "/home1/03076/gzynda/apps/python/conda2.7/envs/ipyrad/lib/python2.7/pkgutil.py", line 472, in find_loader
2019-02-18 11:21:10.613 [IPClusterStart]     for importer in iter_importers(fullname):
2019-02-18 11:21:10.613 [IPClusterStart]   File "/home1/03076/gzynda/apps/python/conda2.7/envs/ipyrad/lib/python2.7/pkgutil.py", line 428, in iter_importers
2019-02-18 11:21:10.613 [IPClusterStart]     __import__(pkg)
2019-02-18 11:21:10.613 [IPClusterStart]   File "/home1/03076/gzynda/apps/python/conda2.7/envs/ipyrad/lib/python2.7/site-packages/ipyparallel/__init__.py", line 17, in <module>
2019-02-18 11:21:10.614 [IPClusterStart]     from .serialize import *
2019-02-18 11:21:10.614 [IPClusterStart]   File "/home1/03076/gzynda/apps/python/conda2.7/envs/ipyrad/lib/python2.7/site-packages/ipyparallel/serialize/__init__.py", line 5, in <module>
2019-02-18 11:21:10.614 [IPClusterStart]     from .serialize import (
2019-02-18 11:21:10.614 [IPClusterStart]   File "/home1/03076/gzynda/apps/python/conda2.7/envs/ipyrad/lib/python2.7/site-packages/ipyparallel/serialize/serialize.py", line 26, in <module>
2019-02-18 11:21:10.615 [IPClusterStart]     from jupyter_client.session import MAX_ITEMS, MAX_BYTES
2019-02-18 11:21:10.615 [IPClusterStart]   File "/home1/03076/gzynda/apps/python/conda2.7/envs/ipyrad/lib/python2.7/site-packages/jupyter_client/__init__.py", line 8, in <module>
2019-02-18 11:21:10.615 [IPClusterStart]     from .blocking import BlockingKernelClient
2019-02-18 11:21:10.615 [IPClusterStart]   File "/home1/03076/gzynda/apps/python/conda2.7/envs/ipyrad/lib/python2.7/site-packages/jupyter_client/blocking/__init__.py", line 1, in <module>
2019-02-18 11:21:10.661 [IPClusterStart]     from .client import BlockingKernelClient
2019-02-18 11:21:10.661 [IPClusterStart]   File "/home1/03076/gzynda/apps/python/conda2.7/envs/ipyrad/lib/python2.7/site-packages/jupyter_client/blocking/client.py", line 13, in <module>
2019-02-18 11:21:10.663 [IPClusterStart]     from queue import Empty  # Python 3
2019-02-18 11:21:10.663 [IPClusterStart]   File "/home1/03076/gzynda/apps/python/conda2.7/envs/ipyrad/lib/python2.7/site-packages/queue/__init__.py", line 1, in <module>
2019-02-18 11:21:10.673 [IPClusterStart]     from __future__ import absolute_import
2019-02-18 11:21:10.674 [IPClusterStart] KeyboardInterrupt
2019-02-18 11:21:10.680 [IPClusterStart] Process '/home1/03076/gzynda/apps/python/conda2.7/envs/ipyrad/bin/python' stopped: {'pid': 39353, 'exit_code': 1}
2019-02-18 11:21:13.613 [IPClusterStart] Removing pid file: /home1/03076/gzynda/.ipython/profile_default/pid/ipcluster.pid
```

It seems to be because [ipyparallel.util.select_random_port](https://github.com/ipython/ipyparallel/blob/master/ipyparallel/util.py#L325) is binding to an invalid address and returning a protected port, as I can demonstrate with the following code

```python
import socket
import zmq

def testSocket(host=''):
        srvsock = socket.socket( socket.AF_INET, socket.SOCK_STREAM)
        srvsock.bind((host, 0))
        addr, port = srvsock.getsockname()
        print("Bound %s:%i"%(addr, port))
        return addr, port

def testZMQ(addr, port):
        context = zmq.Context()
        socket = context.socket(zmq.REP)
        b_address = "tcp://%s:%i" % (addr, port)
        print("PyZmq: attempting to bind %s"%(b_address))
        try:
                socket.bind(b_address)
                print("SUCCESS")
        except Exception as e:
                print("FAILED: %s"%(str(e)))

print("Selecting random port with localhost")
addr, port = testSocket(host='localhost')
testZMQ(addr, port)

HOST = socket.gethostbyname(socket.gethostname())
print("Selecting random port on public network interface")
addr, port = testSocket(host=HOST)
testZMQ(addr, port)

print("Selecting random port on empty host string")
addr, port = testSocket(host='')
testZMQ(addr, port)
```

which returns the following

```
(ipyrad) nid00657(1017)$ python test_sock.py

Selecting random port with localhost
Bound 127.0.0.1:37212
PyZmq: attempting to bind tcp://127.0.0.1:37212
SUCCESS

Selecting random port on public network interface
Bound 10.128.2.150:56924
PyZmq: attempting to bind tcp://10.128.2.150:56924
SUCCESS

Selecting random port on empty host string
Bound 0.0.0.0:92
PyZmq: attempting to bind tcp://0.0.0.0:92
FAILED: Permission denied
```

A simple fix would be to change the empty host string to `localhost`, but I'm not sure what kind of effect that would have on the rest of ipyparallel.

Let me know what you think and if anyone else has ever encountered this.

Thanks,
Greg Zynda

**Comment by tommydevitt** [comment]
I'm having the same issue. Any chance someone might look into this?

Thanks,
Tom Devitt

**Comment by minrk** [comment]
What OS, Python version, and user (root or not)? Port 92 is a privileged port, so not usually bindable by users other than root. I'm surprised that it's binding to such a low port, since that's not in the range where random ports are meant to come from.

ipyparallel should probably allow specifying a port range, when the underlying system can't be trusted to return permissible ports.

From the output of the second one, setting the controller ip address to a public ip instead of '' ought to be a workaround for now.

**Comment by zyndagj** [comment]
## OS

```
nid00019(1002)$ cat /etc/os-release 
NAME="SLES"
VERSION="12-SP3"
VERSION_ID="12.3"
PRETTY_NAME="SUSE Linux Enterprise Server 12 SP3"
ID="sles"
ANSI_COLOR="0;32"
CPE_NAME="cpe:/o:suse:sles:12:sp3"
```

On a Cray XC40

## User

non-root

## Python

```
$ python --version
Python 2.7.15 :: Anaconda, Inc.
```

**Comment by minrk** [comment]
Hi! I’m going through and cleaning up old/stale issues on this repo. Sorry for not responding in a reasonable amount of time!

I'm not quite sure what to do here. We are trusting the system to assign us a port using the OS standard port 0 with the standard empty string for 'all interfaces', but it's assigning us a choice we're not allowed to use. Does it also happen with explicit `'0.0.0.0'` (ipv4 all interfaces)? If that works, then we can switch to that as a workaround, I suppose. If not, I think this is just a system where you can't trust the OS to allocate ports and you must specify all ipcontroller ports explicitly in configuration. Downside: there are a lot!

A configuration option to use consecutive ports for the controller with just a starting port should make this a lot easier.

**Comment by zyndagj** [comment]
Thanks for checking on this! I don't have access to that system anymore, so I won't be able to troubleshoot any further from my end.

**Comment by tommydevitt** [comment]
Thanks for following up. I'm afraid I won't be of much help; that particular machine is being decommissioned.

Tom

**Comment by minrk** [comment]
Thanks for reporting back. I think this is going to be a low priority since it's a very weird issue that doesn't seem to happen on most systems, but my plan at least is going to make the explicit deterministic port range a convenient option so that it's easier to skip random port selection. This is *technically* possible right now, but you need to specify ~15 ports that aren't well organized in the configuration. That's one of the remaining artifacts of the very first version of all this I put together as a student, and wasn't great at making things nice for folks.

**Comment by minrk** [comment]
#565 adds `IPController.ports` so you can specify which ports to use with a single config option, i.e.

ipcontroller --ports=10101-10120

and it will assign those ports in order
