### ISSUE TITLE
Not Implemented Error when trying to start cluster Python 3.8

### ISSUE THREAD

**Issue by ZHIWEN-PING** [ipython/ipyparallel#398]
I'm on windows 10, python 3.8
Error:
C:\WINDOWS\system32>ipcluster start -n 4
2020-03-11 21:33:42.133 [IPClusterStart] Removing pid file: C:\Users\User\.ipython\profile_default\pid\ipcluster.pid
2020-03-11 21:33:42.152 [IPClusterStart] Starting ipcluster with [daemon=False]
2020-03-11 21:33:42.176 [IPClusterStart] Creating pid file: C:\Users\User\.ipython\profile_default\pid\ipcluster.pid
2020-03-11 21:33:42.177 [IPClusterStart] Starting Controller with LocalControllerLauncher
2020-03-11 21:33:42.316 [IPClusterStart] ERROR | Controller start failed
Traceback (most recent call last):
  File "c:\users\user\appdata\local\programs\python\python38\lib\site-packages\ipyparallel\apps\ipclusterapp.py", line 537, in start_controller
    self.controller_launcher.start()
  File "c:\users\user\appdata\local\programs\python\python38\lib\site-packages\ipyparallel\apps\launcher.py", line 339, in start
    return super(LocalControllerLauncher, self).start()
  File "c:\users\user\appdata\local\programs\python\python38\lib\site-packages\ipyparallel\apps\launcher.py", line 269, in start
    self.loop.add_handler(self.stdout, self.handle_stdout, self.loop.READ)
  File "c:\users\user\appdata\local\programs\python\python38\lib\site-packages\tornado\platform\asyncio.py", line 99, in add_handler
    self.asyncio_loop.add_reader(fd, self._handle_events, fd, IOLoop.READ)
  File "c:\users\user\appdata\local\programs\python\python38\lib\asyncio\events.py", line 501, in add_reader
    raise NotImplementedError
NotImplementedError
ERROR:tornado.application:Exception in callback functools.partial(<function IPClusterStart.start.<locals>.start at 0x00000239C75BD8B0>)
Traceback (most recent call last):
  File "c:\users\user\appdata\local\programs\python\python38\lib\site-packages\tornado\ioloop.py", line 743, in _run_callback
    ret = callback()
  File "c:\users\user\appdata\local\programs\python\python38\lib\site-packages\ipyparallel\apps\ipclusterapp.py", line 582, in start
    self.start_controller()
  File "c:\users\user\appdata\local\programs\python\python38\lib\site-packages\ipyparallel\apps\ipclusterapp.py", line 537, in start_controller
    self.controller_launcher.start()
  File "c:\users\user\appdata\local\programs\python\python38\lib\site-packages\ipyparallel\apps\launcher.py", line 339, in start
    return super(LocalControllerLauncher, self).start()
  File "c:\users\user\appdata\local\programs\python\python38\lib\site-packages\ipyparallel\apps\launcher.py", line 269, in start
    self.loop.add_handler(self.stdout, self.handle_stdout, self.loop.READ)
  File "c:\users\user\appdata\local\programs\python\python38\lib\site-packages\tornado\platform\asyncio.py", line 99, in add_handler
    self.asyncio_loop.add_reader(fd, self._handle_events, fd, IOLoop.READ)
  File "c:\users\user\appdata\local\programs\python\python38\lib\asyncio\events.py", line 501, in add_reader
    raise NotImplementedError

**Comment by bgeneto** [comment]
Some problem here... did you find a solution?

**Comment by marecabo** [comment]
This seems to be a known issue with asyncio for Python 3.8, see https://github.com/tornadoweb/tornado/issues/2608. This (https://github.com/tornadoweb/tornado/issues/2608#issuecomment-550180288) comment solved this issue for me.

**Comment by gamis** [comment]
Thanks @marecabo ! I'll have to try that some time. For now, I've moved onto using Dask Distributed instead. It's very nice.

**Comment by marecabo** [comment]
This issue was resolved for me after updating tornado to 6.1 as proposed here: https://github.com/tornadoweb/tornado/issues/2608#issuecomment-736185273

**Comment by minrk** [comment]
As mentioned, this is fixed by tornado 6.1
