### ISSUE TITLE
Repeated "ipcontroller" in filenames with cid in 6.2.5

### ISSUE THREAD

**Issue by gsganden** [ipython/ipyparallel#408]
# Traceback

```
Waiting for connection file: ~/.ipython/profile_default/security/ipcontroller-test-client.json
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/Users/gGandenberger/.pyenv/versions/ipytest/lib/python3.7/site-packages/ipyparallel/client/client.py", line 417, in __init__
    raise IOError(msg)
OSError: Connection file '~/.ipython/profile_default/security/ipcontroller-test-client.json' not found.
You have attempted to connect to an IPython Cluster but no Controller could be found.
Please double-check your configuration and ensure that a cluster is running.
```

# Steps to reproduce

```bash
pip install "ipyparallel==6.2.5"
ipcluster start -n 4 --cluster-id=test
```

In a different terminal session:

```bash
python -c "import ipyparallel; ipyparallel.Client(timeout=10, cluster_id='test')"
```

Changing `pip install "ipyparallel==6.2.5"` to `pip install "ipyparallel==6.2.4"` resolves the problem.

# Diagnosis

`ipcluster` is creating filenames that start with TWO instances of "ipcontroller," e.g. "~/.ipython/profile_default/security/ipcontrolleripcontroller-test-client.json".

**Comment by minrk** [comment]
closed by #407
