### ISSUE TITLE
SSH engine_cmd has to be a list instead of a string

### ISSUE THREAD

**Issue by csala** [ipython/ipyparallel#47]
Current version fails to start when specifying an `engine_cmd` with a string like the documentation suggests.

For example:

    #------------------------------------------------------------------------------
    # SSHEngineLauncher configuration
    #------------------------------------------------------------------------------
    c.SSHEngineSetLauncher.engines = {
        'hostname01': {
            'n': 8,
            'engine_cmd': '/home/user/bin/ipengine',
        }
    }

Produces the following output:

```
$ ipcluster start
2015-10-01 15:30:49.911 [IPClusterStart] Starting ipcluster with [daemon=False]
2015-10-01 15:30:49.912 [IPClusterStart] Creating pid file: /home/user/.ipython/profile_default/pid/ipcluster.pid
2015-10-01 15:30:49.912 [IPClusterStart] Starting Controller with LocalControllerLauncher
2015-10-01 15:30:50.914 [IPClusterStart] Starting 8 Engines with SSH
2015-10-01 15:30:50.917 [IPClusterStart] ERROR | Engine start failed
Traceback (most recent call last):
  File "/home/user/.virtualenvs/ipyparallel/local/lib/python2.7/site-packages/ipyparallel/apps/ipclusterapp.py", line 332, in start_engines
    self.engine_launcher.start(self.n)
  File "/home/user/.virtualenvs/ipyparallel/local/lib/python2.7/site-packages/ipyparallel/apps/launcher.py", line 790, in start
    el.engine_cmd = cmd
  File "/home/user/.virtualenvs/ipyparallel/local/lib/python2.7/site-packages/traitlets/traitlets.py", line 450, in __set__
    new_value = self._validate(obj, value)
  File "/home/user/.virtualenvs/ipyparallel/local/lib/python2.7/site-packages/traitlets/traitlets.py", line 471, in _validate
    value = self.validate(obj, value)
  File "/home/user/.virtualenvs/ipyparallel/local/lib/python2.7/site-packages/traitlets/traitlets.py", line 1624, in validate
    value = super(List, self).validate(obj, value)
  File "/home/user/.virtualenvs/ipyparallel/local/lib/python2.7/site-packages/traitlets/traitlets.py", line 1542, in validate
    value = super(Container, self).validate(obj, value)
  File "/home/user/.virtualenvs/ipyparallel/local/lib/python2.7/site-packages/traitlets/traitlets.py", line 1045, in validate
    self.error(obj, value)
  File "/home/user/.virtualenvs/ipyparallel/local/lib/python2.7/site-packages/traitlets/traitlets.py", line 899, in error
    raise TraitError(e)
TraitError: The 'engine_cmd' trait of a SSHEngineLauncher instance must be a list, but a value of type 'str' (i.e. '/home/user/bin/ipengine') was specified.
ERROR:tornado.application:Exception in callback <functools.partial object at 0x7fb639149e10>
Traceback (most recent call last):
  File "/home/user/.virtualenvs/ipyparallel/local/lib/python2.7/site-packages/tornado/ioloop.py", line 592, in _run_callback
    ret = callback()
  File "/home/user/.virtualenvs/ipyparallel/local/lib/python2.7/site-packages/tornado/stack_context.py", line 275, in null_wrapper
    return fn(*args, **kwargs)
  File "/home/user/.virtualenvs/ipyparallel/local/lib/python2.7/site-packages/ipyparallel/apps/ipclusterapp.py", line 332, in start_engines
    self.engine_launcher.start(self.n)
  File "/home/user/.virtualenvs/ipyparallel/local/lib/python2.7/site-packages/ipyparallel/apps/launcher.py", line 790, in start
    el.engine_cmd = cmd
  File "/home/user/.virtualenvs/ipyparallel/local/lib/python2.7/site-packages/traitlets/traitlets.py", line 450, in __set__
    new_value = self._validate(obj, value)
  File "/home/user/.virtualenvs/ipyparallel/local/lib/python2.7/site-packages/traitlets/traitlets.py", line 471, in _validate
    value = self.validate(obj, value)
  File "/home/user/.virtualenvs/ipyparallel/local/lib/python2.7/site-packages/traitlets/traitlets.py", line 1624, in validate
    value = super(List, self).validate(obj, value)
  File "/home/user/.virtualenvs/ipyparallel/local/lib/python2.7/site-packages/traitlets/traitlets.py", line 1542, in validate
    value = super(Container, self).validate(obj, value)
  File "/home/user/.virtualenvs/ipyparallel/local/lib/python2.7/site-packages/traitlets/traitlets.py", line 1045, in validate
    self.error(obj, value)
  File "/home/user/.virtualenvs/ipyparallel/local/lib/python2.7/site-packages/traitlets/traitlets.py", line 899, in error
    raise TraitError(e)
TraitError: The 'engine_cmd' trait of a SSHEngineLauncher instance must be a list, but a value of type 'str' (i.e. '/home/user/bin/ipengine') was specified.
```

Solution may be either encapsulating the value of `cmd` inside a `list` in case it is a string, or changing the documentation to indicate that `engine_cmd` must be a list.

**Comment by minrk** [comment]
Docs updated in #48
