### ISSUE TITLE
6.3.0: pytest is failing

### ISSUE THREAD

**Issue by kloczek** [ipython/ipyparallel#529]
Just normal build, install and test cycle used on building package from non-root account:
- "setup.py build"
- "setup.py install --root </install/prefix>"
- "pytest with PYTHONPATH pointing to setearch and sitelib inside </install/prefix>
```console
+ PYTHONPATH=/home/tkloczko/rpmbuild/BUILDROOT/python-ipyparallel-6.3.0-8.fc35.x86_64/usr/lib64/python3.8/site-packages:/home/tkloczko/rpmbuild/BUILDROOT/python-ipyparallel-6.3.0-8.fc35.x86_64/usr/lib/python3.8/site-packages
+ /usr/bin/pytest -ra
=========================================================================== test session starts ============================================================================
platform linux -- Python 3.8.11, pytest-6.2.4, py-1.10.0, pluggy-0.13.1
benchmark: 3.4.1 (defaults: timer=time.perf_counter disable_gc=False min_rounds=5 min_time=0.000005 max_time=1.0 calibration_precision=10 warmup=False warmup_iterations=100000)
rootdir: /home/tkloczko/rpmbuild/BUILD/ipyparallel-6.3.0
plugins: forked-1.3.0, shutil-1.7.0, virtualenv-1.7.0, expect-1.1.0, httpbin-1.0.0, flake8-1.0.7, timeout-1.4.2, betamax-0.8.1, freezegun-0.4.2, case-1.5.3, isort-1.3.0, aspectlib-1.5.2, asyncio-0.15.1, toolbox-0.5, xprocess-0.17.1, aiohttp-0.3.0, checkdocs-2.7.0, mock-3.6.1, rerunfailures-9.1.1, requests-mock-1.9.3, cov-2.12.1, pyfakefs-4.5.0, flaky-3.7.0, hypothesis-6.14.0, benchmark-3.4.1, xdist-2.3.0, pylama-7.7.1, datadir-1.3.1, regressions-2.2.0, cases-3.6.3, Faker-8.10.0
collected 332 items

. .                                                                                                                                                                  [  0%]
ipyparallel/tests/test_apps.py ..                                                                                                                                    [  0%]
ipyparallel/tests/test_asyncresult.py ..............................                                                                                                 [  9%]
ipyparallel/tests/test_canning.py .......                                                                                                                            [ 12%]
ipyparallel/tests/test_client.py ...s......................................                                                                                          [ 24%]
ipyparallel/tests/test_db.py ................................                                                                                                        [ 34%]
ipyparallel/tests/test_dependency.py .....                                                                                                                           [ 35%]
ipyparallel/tests/test_executor.py .....                                                                                                                             [ 37%]
ipyparallel/tests/test_joblib.py sss                                                                                                                                 [ 38%]
ipyparallel/tests/test_launcher.py ...........................s..............................s..s....s...........                                                    [ 61%]
ipyparallel/tests/test_lbview.py ..............X                                                                                                                     [ 66%]
ipyparallel/tests/test_magics.py ..........s..                                                                                                                       [ 70%]
ipyparallel/tests/test_mongodb.py ssssssssssssss                                                                                                                     [ 74%]
ipyparallel/tests/test_remotefunction.py ...                                                                                                                         [ 75%]
ipyparallel/tests/test_serialize.py ...............                                                                                                                  [ 80%]
ipyparallel/tests/test_util.py .                                                                                                                                     [ 80%]
ipyparallel/tests/test_view.py ..............................s..............................Exception ignored in: <function BaseEventLoop.__del__ at 0x7f1789a8d1f0>
Traceback (most recent call last):
  File "/usr/lib64/python3.8/asyncio/base_events.py", line 656, in __del__
    self.close()
  File "/usr/lib64/python3.8/asyncio/unix_events.py", line 58, in close
    super().close()
  File "/usr/lib64/python3.8/asyncio/selector_events.py", line 92, in close
    self._close_self_pipe()
  File "/usr/lib64/python3.8/asyncio/selector_events.py", line 99, in _close_self_pipe
    self._remove_reader(self._ssock.fileno())
AttributeError: '_UnixSelectorEventLoop' object has no attribute '_ssock'
FException ignored in: <function BaseEventLoop.__del__ at 0x7f1789a8d1f0>
Traceback (most recent call last):
  File "/usr/lib64/python3.8/asyncio/base_events.py", line 656, in __del__
    self.close()
  File "/usr/lib64/python3.8/asyncio/unix_events.py", line 58, in close
    super().close()
  File "/usr/lib64/python3.8/asyncio/selector_events.py", line 92, in close
    self._close_self_pipe()
  File "/usr/lib64/python3.8/asyncio/selector_events.py", line 99, in _close_self_pipe
    self._remove_reader(self._ssock.fileno())
AttributeError: '_UnixSelectorEventLoop' object has no attribute '_ssock'
FException ignored in: <function BaseEventLoop.__del__ at 0x7f1789a8d1f0>
Traceback (most recent call last):
  File "/usr/lib64/python3.8/asyncio/base_events.py", line 656, in __del__
    self.close()
  File "/usr/lib64/python3.8/asyncio/unix_events.py", line 58, in close
    super().close()
  File "/usr/lib64/python3.8/asyncio/selector_events.py", line 92, in close
    self._close_self_pipe()
  File "/usr/lib64/python3.8/asyncio/selector_events.py", line 99, in _close_self_pipe
    self._remove_reader(self._ssock.fileno())
AttributeError: '_UnixSelectorEventLoop' object has no attribute '_ssock'
xException ignored in: <function BaseEventLoop.__del__ at 0x7f1789a8d1f0>
Traceback (most recent call last):
  File "/usr/lib64/python3.8/asyncio/base_events.py", line 656, in __del__
    self.close()
  File "/usr/lib64/python3.8/asyncio/unix_events.py", line 58, in close
    super().close()
  File "/usr/lib64/python3.8/asyncio/selector_events.py", line 92, in close
    self._close_self_pipe()
  File "/usr/lib64/python3.8/asyncio/selector_events.py", line 99, in _close_self_pipe
    self._remove_reader(self._ssock.fileno())
AttributeError: '_UnixSelectorEventLoop' object has no attribute '_ssock'
x                                                                     [100%]

================================================================================= FAILURES =================================================================================
____________________________________________________________________ TestView.test_unicode_apply_result ____________________________________________________________________

self = <ipyparallel.tests.test_view.TestView testMethod=test_unicode_apply_result>

    def setUp(self):
        # On Win XP, wait for resource cleanup, else parallel test group fails
        if platform.system() == "Windows" and platform.win32_ver()[0] == "XP":
            # 1 sec fails. 1.5 sec seems ok. Using 2 sec for margin of safety
            time.sleep(2)
>       super(TestView, self).setUp()

ipyparallel/tests/test_view.py:41:
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
ipyparallel/tests/clienttest.py:163: in setUp
    self.client = self.connect_client()
ipyparallel/tests/clienttest.py:129: in connect_client
    c = Client(profile='iptest', context=self.context)
ipyparallel/client/client.py:519: in __init__
    self._connect(sshserver, ssh_kwargs, timeout)
ipyparallel/client/client.py:669: in _connect
    self._start_io_thread()
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

self = <ipyparallel.client.client.Client object at 0x7f17247a1100>

    def _start_io_thread(self):
        """Start IOLoop in a background thread."""
        evt = Event()
        self._io_thread = Thread(target=self._io_main, args=(evt,))
        self._io_thread.daemon = True
        self._io_thread.start()
        # wait for the IOLoop to start
        for i in range(10):
            if evt.wait(1):
                return
            if not self._io_thread.is_alive():
>               raise RuntimeError("IO Loop failed to start")
E               RuntimeError: IO Loop failed to start

ipyparallel/client/client.py:896: RuntimeError
--------------------------------------------------------------------------- Captured stderr call ---------------------------------------------------------------------------
2021-07-15 13:21:43.141 [IPControllerApp] client::client b'\x00k\x8bF\xe0' requested 'connection_request'
2021-07-15 13:21:43.141 [IPControllerApp] client::client [b'\x00k\x8bF\xe0'] connected
2021-07-15 13:21:43.156 [IPControllerApp] client::client b'\x00k\x8bF\xe1' requested 'connection_request'
2021-07-15 13:21:43.156 [IPControllerApp] client::client [b'\x00k\x8bF\xe1'] connected
______________________________________________________________________ TestView.test_unicode_execute _______________________________________________________________________

self = <ipyparallel.tests.test_view.TestView testMethod=test_unicode_execute>

    def setUp(self):
        # On Win XP, wait for resource cleanup, else parallel test group fails
        if platform.system() == "Windows" and platform.win32_ver()[0] == "XP":
            # 1 sec fails. 1.5 sec seems ok. Using 2 sec for margin of safety
            time.sleep(2)
>       super(TestView, self).setUp()

ipyparallel/tests/test_view.py:41:
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
ipyparallel/tests/clienttest.py:161: in setUp
    add_engines(self.engine_count, total=True)
ipyparallel/tests/__init__.py:82: in add_engines
    rc = Client(profile=profile)
ipyparallel/client/client.py:519: in __init__
    self._connect(sshserver, ssh_kwargs, timeout)
ipyparallel/client/client.py:669: in _connect
    self._start_io_thread()
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

self = <ipyparallel.client.client.Client object at 0x7f17244bd9d0>

    def _start_io_thread(self):
        """Start IOLoop in a background thread."""
        evt = Event()
        self._io_thread = Thread(target=self._io_main, args=(evt,))
        self._io_thread.daemon = True
        self._io_thread.start()
        # wait for the IOLoop to start
        for i in range(10):
            if evt.wait(1):
                return
            if not self._io_thread.is_alive():
>               raise RuntimeError("IO Loop failed to start")
E               RuntimeError: IO Loop failed to start

ipyparallel/client/client.py:896: RuntimeError
--------------------------------------------------------------------------- Captured stderr call ---------------------------------------------------------------------------
2021-07-15 13:21:44.420 [IPControllerApp] client::client b'\x00k\x8bF\xe2' requested 'connection_request'
2021-07-15 13:21:44.421 [IPControllerApp] client::client [b'\x00k\x8bF\xe2'] connected
============================================================================= warnings summary =============================================================================
ipyparallel/tests/test_magics.py::TestParallelMagics::test_autopx_blocking
ipyparallel/tests/test_magics.py::TestParallelMagics::test_autopx_nonblocking
  /home/tkloczko/rpmbuild/BUILD/ipyparallel-6.3.0/ipyparallel/client/magics.py:388: DeprecationWarning: "@coroutine" decorator is deprecated since Python 3.8, use "async def" instead
    pxrun_nodes = coroutine(pxrun_nodes)

ipyparallel/tests/test_serialize.py::test_numpy
  /home/tkloczko/rpmbuild/BUILD/ipyparallel-6.3.0/ipyparallel/tests/test_serialize.py:79: DeprecationWarning: Importing from numpy.testing.utils is deprecated since 1.15.0, import from numpy.testing instead.
    from numpy.testing.utils import assert_array_equal

ipyparallel/tests/test_view.py::TestView::test_unicode_apply_result
  /usr/lib/python3.8/site-packages/_pytest/threadexception.py:75: PytestUnhandledThreadExceptionWarning: Exception in thread Thread-558

  Traceback (most recent call last):
    File "/usr/lib64/python3.8/threading.py", line 932, in _bootstrap_inner
      self.run()
    File "/usr/lib64/python3.8/threading.py", line 870, in run
      self._target(*self._args, **self._kwargs)
    File "/home/tkloczko/rpmbuild/BUILD/ipyparallel-6.3.0/ipyparallel/client/client.py", line 902, in _io_main
      self._io_loop = self._make_io_loop()
    File "/home/tkloczko/rpmbuild/BUILD/ipyparallel-6.3.0/ipyparallel/client/client.py", line 860, in _make_io_loop
      loop = ioloop.IOLoop()
    File "/usr/lib64/python3.8/site-packages/tornado/util.py", line 288, in __new__
      instance.initialize(*args, **init_kwargs)
    File "/usr/lib64/python3.8/site-packages/tornado/platform/asyncio.py", line 309, in initialize
      loop = asyncio.new_event_loop()
    File "/usr/lib64/python3.8/asyncio/events.py", line 758, in new_event_loop
      return get_event_loop_policy().new_event_loop()
    File "/usr/lib64/python3.8/asyncio/events.py", line 656, in new_event_loop
      return self._loop_factory()
    File "/usr/lib64/python3.8/asyncio/unix_events.py", line 54, in __init__
      super().__init__(selector)
    File "/usr/lib64/python3.8/asyncio/selector_events.py", line 58, in __init__
      selector = selectors.DefaultSelector()
    File "/usr/lib64/python3.8/selectors.py", line 349, in __init__
      self._selector = self._selector_cls()
  OSError: [Errno 24] Too many open files

    warnings.warn(pytest.PytestUnhandledThreadExceptionWarning(msg))

ipyparallel/tests/test_view.py::TestView::test_unicode_execute
  /usr/lib/python3.8/site-packages/_pytest/threadexception.py:75: PytestUnhandledThreadExceptionWarning: Exception in thread Thread-559

  Traceback (most recent call last):
    File "/home/tkloczko/rpmbuild/BUILD/ipyparallel-6.3.0/ipyparallel/client/client.py", line 855, in _make_io_loop
      asyncio.get_event_loop()
    File "/usr/lib64/python3.8/asyncio/events.py", line 639, in get_event_loop
      raise RuntimeError('There is no current event loop in thread %r.'
  RuntimeError: There is no current event loop in thread 'Thread-559'.

  During handling of the above exception, another exception occurred:

  Traceback (most recent call last):
    File "/usr/lib64/python3.8/threading.py", line 932, in _bootstrap_inner
      self.run()
    File "/usr/lib64/python3.8/threading.py", line 870, in run
      self._target(*self._args, **self._kwargs)
    File "/home/tkloczko/rpmbuild/BUILD/ipyparallel-6.3.0/ipyparallel/client/client.py", line 902, in _io_main
      self._io_loop = self._make_io_loop()
    File "/home/tkloczko/rpmbuild/BUILD/ipyparallel-6.3.0/ipyparallel/client/client.py", line 859, in _make_io_loop
      asyncio.set_event_loop(asyncio.new_event_loop())
    File "/usr/lib64/python3.8/asyncio/events.py", line 758, in new_event_loop
      return get_event_loop_policy().new_event_loop()
    File "/usr/lib64/python3.8/asyncio/events.py", line 656, in new_event_loop
      return self._loop_factory()
    File "/usr/lib64/python3.8/asyncio/unix_events.py", line 54, in __init__
      super().__init__(selector)
    File "/usr/lib64/python3.8/asyncio/selector_events.py", line 58, in __init__
      selector = selectors.DefaultSelector()
    File "/usr/lib64/python3.8/selectors.py", line 349, in __init__
      self._selector = self._selector_cls()
  OSError: [Errno 24] Too many open files

    warnings.warn(pytest.PytestUnhandledThreadExceptionWarning(msg))

ipyparallel/tests/test_view.py::TestView::test_use_cloudpickle
  /usr/lib/python3.8/site-packages/_pytest/threadexception.py:75: PytestUnhandledThreadExceptionWarning: Exception in thread Thread-560

  Traceback (most recent call last):
    File "/home/tkloczko/rpmbuild/BUILD/ipyparallel-6.3.0/ipyparallel/client/client.py", line 855, in _make_io_loop
      asyncio.get_event_loop()
    File "/usr/lib64/python3.8/asyncio/events.py", line 639, in get_event_loop
      raise RuntimeError('There is no current event loop in thread %r.'
  RuntimeError: There is no current event loop in thread 'Thread-560'.

  During handling of the above exception, another exception occurred:

  Traceback (most recent call last):
    File "/usr/lib64/python3.8/threading.py", line 932, in _bootstrap_inner
      self.run()
    File "/usr/lib64/python3.8/threading.py", line 870, in run
      self._target(*self._args, **self._kwargs)
    File "/home/tkloczko/rpmbuild/BUILD/ipyparallel-6.3.0/ipyparallel/client/client.py", line 902, in _io_main
      self._io_loop = self._make_io_loop()
    File "/home/tkloczko/rpmbuild/BUILD/ipyparallel-6.3.0/ipyparallel/client/client.py", line 859, in _make_io_loop
      asyncio.set_event_loop(asyncio.new_event_loop())
    File "/usr/lib64/python3.8/asyncio/events.py", line 758, in new_event_loop
      return get_event_loop_policy().new_event_loop()
    File "/usr/lib64/python3.8/asyncio/events.py", line 656, in new_event_loop
      return self._loop_factory()
    File "/usr/lib64/python3.8/asyncio/unix_events.py", line 54, in __init__
      super().__init__(selector)
    File "/usr/lib64/python3.8/asyncio/selector_events.py", line 58, in __init__
      selector = selectors.DefaultSelector()
    File "/usr/lib64/python3.8/selectors.py", line 349, in __init__
      self._selector = self._selector_cls()
  OSError: [Errno 24] Too many open files

    warnings.warn(pytest.PytestUnhandledThreadExceptionWarning(msg))

ipyparallel/tests/test_view.py::TestView::test_z_crash_mux
  /usr/lib/python3.8/site-packages/_pytest/threadexception.py:75: PytestUnhandledThreadExceptionWarning: Exception in thread Thread-561

  Traceback (most recent call last):
    File "/home/tkloczko/rpmbuild/BUILD/ipyparallel-6.3.0/ipyparallel/client/client.py", line 855, in _make_io_loop
      asyncio.get_event_loop()
    File "/usr/lib64/python3.8/asyncio/events.py", line 639, in get_event_loop
      raise RuntimeError('There is no current event loop in thread %r.'
  RuntimeError: There is no current event loop in thread 'Thread-561'.

  During handling of the above exception, another exception occurred:

  Traceback (most recent call last):
    File "/usr/lib64/python3.8/threading.py", line 932, in _bootstrap_inner
      self.run()
    File "/usr/lib64/python3.8/threading.py", line 870, in run
      self._target(*self._args, **self._kwargs)
    File "/home/tkloczko/rpmbuild/BUILD/ipyparallel-6.3.0/ipyparallel/client/client.py", line 902, in _io_main
      self._io_loop = self._make_io_loop()
    File "/home/tkloczko/rpmbuild/BUILD/ipyparallel-6.3.0/ipyparallel/client/client.py", line 859, in _make_io_loop
      asyncio.set_event_loop(asyncio.new_event_loop())
    File "/usr/lib64/python3.8/asyncio/events.py", line 758, in new_event_loop
      return get_event_loop_policy().new_event_loop()
    File "/usr/lib64/python3.8/asyncio/events.py", line 656, in new_event_loop
      return self._loop_factory()
    File "/usr/lib64/python3.8/asyncio/unix_events.py", line 54, in __init__
      super().__init__(selector)
    File "/usr/lib64/python3.8/asyncio/selector_events.py", line 58, in __init__
      selector = selectors.DefaultSelector()
    File "/usr/lib64/python3.8/selectors.py", line 349, in __init__
      self._selector = self._selector_cls()
  OSError: [Errno 24] Too many open files

    warnings.warn(pytest.PytestUnhandledThreadExceptionWarning(msg))

-- Docs: https://docs.pytest.org/en/stable/warnings.html
========================================================================= short test summary info ==========================================================================
SKIPPED [1] ipyparallel/tests/clienttest.py:87: Test requires distributed
SKIPPED [3] ipyparallel/tests/test_joblib.py:26: Requires joblib >= 0.10
SKIPPED [3] ipyparallel/tests/test_launcher.py:82: SSH Launchers don't support cluster ID
SKIPPED [1] ipyparallel/tests/test_launcher.py:160: SSH Launchers don't support cluster ID
SKIPPED [1] ipyparallel/tests/test_magics.py:290: could not import 'matplotlib': No module named 'matplotlib'
SKIPPED [14] ipyparallel/tests/test_mongodb.py:21: Requires mongodb
SKIPPED [1] ipyparallel/tests/test_view.py:665: could not import 'matplotlib': No module named 'matplotlib'
XFAIL ipyparallel/tests/test_view.py::TestView::test_use_cloudpickle
  cloudpickle doesn't seem to work right now
XFAIL ipyparallel/tests/test_view.py::TestView::test_z_crash_mux
XPASS ipyparallel/tests/test_lbview.py::TestLoadBalancedView::test_z_crash_task
FAILED ipyparallel/tests/test_view.py::TestView::test_unicode_apply_result - RuntimeError: IO Loop failed to start
FAILED ipyparallel/tests/test_view.py::TestView::test_unicode_execute - RuntimeError: IO Loop failed to start
========================================== 2 failed, 302 passed, 24 skipped, 2 xfailed, 1 xpassed, 7 warnings in 96.26s (0:01:36) ==========================================
```

**Comment by minrk** [comment]
Can you reproduce this with 7.0.0a5?

**Comment by minrk** [comment]
Yes, jupyter-packaging and jupyterlab are required to run the labextension builds. jupyter-packaging doesn't require unittest2, though. #559 vendors jupyter-packaging so it's not an external dependency.

**Comment by kloczek** [comment]
Just tested 8.0.0 and pytest is failing in ipcluster command execution
```console
+ PYTHONPATH=/home/tkloczko/rpmbuild/BUILDROOT/python-ipyparallel-8.0.0-2.fc35.x86_64/usr/lib64/python3.8/site-packages:/home/tkloczko/rpmbuild/BUILDROOT/python-ipyparallel-8.0.0-2.fc35.x86_64/usr/lib/python3.8/site-packages
+ /usr/bin/pytest -ra
=========================================================================== test session starts ============================================================================
platform linux -- Python 3.8.12, pytest-6.2.5, py-1.10.0, pluggy-0.13.1
rootdir: /home/tkloczko/rpmbuild/BUILD/ipyparallel-8.0.0
plugins: rerunfailures-9.1.1, cov-2.12.1, forked-1.3.0, xdist-2.3.0, flake8-1.0.7, shutil-1.7.0, virtualenv-1.7.0, trio-0.7.0, mock-3.6.1, timeout-2.0.1, anyio-3.3.1, tornado-0.8.1
collected 479 items / 1 error / 478 selected

================================================================================== ERRORS ==================================================================================
_______________________________________________________________ ERROR collecting benchmarks/engines_test.py ________________________________________________________________
benchmarks/engines_test.py:9: in <module>
    check_call(f'ipcluster start -n {n} --daemon --profile=asv --debug', shell=True)
/usr/lib64/python3.8/subprocess.py:364: in check_call
    raise CalledProcessError(retcode, cmd)
E   subprocess.CalledProcessError: Command 'ipcluster start -n 20 --daemon --profile=asv --debug' returned non-zero exit status 2.
----------------------------------------------------------------------------- Captured stderr ------------------------------------------------------------------------------
usage: ipcluster [-h] [--debug] [--quiet] [--init]
                 [--profile-dir ProfileDir.location]
                 [--profile IPClusterStart.profile]
                 [--ipython-dir IPClusterStart.ipython_dir]
                 [--log-level IPClusterStart.log_level]
                 [--config IPClusterStart.extra_config_file]
                 [--work-dir IPClusterStart.work_dir]
                 [--log-to-file [IPClusterStart.log_to_file]]
                 [--clean-logs IPClusterStart.clean_logs]
                 [--log-url IPClusterStart.log_url]
                 [--cluster-id IPClusterStart.cluster_id] [-n Cluster.n]
                 [--engines Cluster.engine_launcher_class]
                 [--daemonize [IPClusterStart.daemonize]]
                 [--delay Cluster.delay]
                 [--controller Cluster.controller_launcher_class]
                 [--ip Cluster.controller_ip]
                 [--location Cluster.controller_location]
                 [extra_args [extra_args ...]]
ipcluster: error: argument --daemon: expected one argument
============================================================================= warnings summary =============================================================================
../../../../../usr/lib/python3.8/site-packages/_pytest/nodes.py:274
  /usr/lib/python3.8/site-packages/_pytest/nodes.py:274: PytestUnknownMarkWarning: Unknown pytest.mark.asyncio - is this a typo?  You can register custom marks to avoid this warning - for details, see https://docs.pytest.org/en/stable/mark.html
    marker_ = getattr(MARK_GEN, marker)

-- Docs: https://docs.pytest.org/en/stable/warnings.html
========================================================================= short test summary info ==========================================================================
ERROR benchmarks/engines_test.py - subprocess.CalledProcessError: Command 'ipcluster start -n 20 --daemon --profile=asv --debug' returned non-zero exit status 2.
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!! Interrupted: 1 error during collection !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
======================================================================= 1 warning, 1 error in 4.30s ========================================================================
```

**Comment by kloczek** [comment]
However look slike after igmnore that single file everything else is OK.
```console
+ PYTHONPATH=/home/tkloczko/rpmbuild/BUILDROOT/python-ipyparallel-8.0.0-2.fc35.x86_64/usr/lib64/python3.8/site-packages:/home/tkloczko/rpmbuild/BUILDROOT/python-ipyparallel-8.0.0-2.fc35.x86_64/usr/lib/python3.8/site-packages
+ /usr/bin/pytest -ra -p no:pytest-relaxed -p no:randomly --ignore benchmarks/engines_test.py
=========================================================================== test session starts ============================================================================
platform linux -- Python 3.8.12, pytest-6.2.5, py-1.10.0, pluggy-0.13.1
rootdir: /home/tkloczko/rpmbuild/BUILD/ipyparallel-8.0.0
plugins: rerunfailures-9.1.1, cov-2.12.1, forked-1.3.0, xdist-2.3.0, flake8-1.0.7, shutil-1.7.0, virtualenv-1.7.0, trio-0.7.0, mock-3.6.1, timeout-2.0.1, anyio-3.3.1, tornado-0.8.1, asyncio-0.15.1
collected 479 items

ipyparallel/tests/test_apps.py ................                                                                                                                      [  3%]
ipyparallel/tests/test_async.py ....                                                                                                                                 [  4%]
ipyparallel/tests/test_asyncresult.py ....................................                                                                                           [ 11%]
ipyparallel/tests/test_canning.py .........                                                                                                                          [ 13%]
ipyparallel/tests/test_client.py ...s..........................................                                                                                      [ 23%]
ipyparallel/tests/test_cluster.py ....................                                                                                                               [ 27%]
ipyparallel/tests/test_db.py ................................                                                                                                        [ 34%]
ipyparallel/tests/test_dependency.py .....                                                                                                                           [ 35%]
ipyparallel/tests/test_executor.py .....                                                                                                                             [ 36%]
ipyparallel/tests/test_joblib.py sss                                                                                                                                 [ 36%]
ipyparallel/tests/test_launcher.py .............................................................................                                                     [ 52%]
ipyparallel/tests/test_lbview.py ...................                                                                                                                 [ 56%]
ipyparallel/tests/test_magics.py .............s..                                                                                                                    [ 60%]
ipyparallel/tests/test_mongodb.py ssssssssssssss                                                                                                                     [ 63%]
ipyparallel/tests/test_mpi.py .....                                                                                                                                  [ 64%]
ipyparallel/tests/test_remotefunction.py ...                                                                                                                         [ 64%]
ipyparallel/tests/test_serialize.py ...............                                                                                                                  [ 67%]
ipyparallel/tests/test_slurm.py sssss                                                                                                                                [ 68%]
ipyparallel/tests/test_ssh.py ssssssssss                                                                                                                             [ 70%]
ipyparallel/tests/test_util.py .                                                                                                                                     [ 71%]
ipyparallel/tests/test_view.py .............ss..................s................................s.                                                                  [ 85%]
ipyparallel/tests/test_view_broadcast.py ..X..........ss...................sXXXXXX..................X...x....s.                                                      [100%]

============================================================================= warnings summary =============================================================================
ipyparallel/tests/test_db.py: 14 warnings
  /usr/lib64/python3.8/json/encoder.py:257: UserWarning: date_default is deprecated since jupyter_client 7.0.0. Use jupyter_client.jsonutil.json_default.
    return _iterencode(o, 0)

-- Docs: https://docs.pytest.org/en/stable/warnings.html
========================================================================= short test summary info ==========================================================================
SKIPPED [1] ipyparallel/tests/clienttest.py:85: Test requires distributed
SKIPPED [3] ipyparallel/tests/test_joblib.py:25: Requires joblib >= 0.10
SKIPPED [1] ipyparallel/tests/test_magics.py:415: could not import 'matplotlib': No module named 'matplotlib'
SKIPPED [14] ipyparallel/tests/test_mongodb.py:20: Requires mongodb
SKIPPED [5] ipyparallel/tests/test_slurm.py:18: Requires slurm
SKIPPED [10] ipyparallel/tests/conftest.py:171: Needs docker compose
SKIPPED [6] ipyparallel/tests/clienttest.py:85: Test requires cloudpickle
SKIPPED [2] ipyparallel/tests/test_view.py:689: could not import 'matplotlib': No module named 'matplotlib'
XFAIL ipyparallel/tests/test_view_broadcast.py::TestBroadcastViewCoalescing::test_target_ordering
  coalescing view doesn't preserve target order
XPASS ipyparallel/tests/test_view_broadcast.py::TestBroadcastViewCoalescing::test_apply_displaypub displaypub ordering not preserved
XPASS ipyparallel/tests/test_view_broadcast.py::TestBroadcastViewCoalescing::test_map map not yet implemented
XPASS ipyparallel/tests/test_view_broadcast.py::TestBroadcastViewCoalescing::test_map_empty_sequence map not yet implemented
XPASS ipyparallel/tests/test_view_broadcast.py::TestBroadcastViewCoalescing::test_map_iterable map not yet implemented
XPASS ipyparallel/tests/test_view_broadcast.py::TestBroadcastViewCoalescing::test_map_numpy map not yet implemented
XPASS ipyparallel/tests/test_view_broadcast.py::TestBroadcastViewCoalescing::test_map_ref map not yet implemented
XPASS ipyparallel/tests/test_view_broadcast.py::TestBroadcastViewCoalescing::test_map_reference map not yet implemented
XPASS ipyparallel/tests/test_view_broadcast.py::TestBroadcastViewCoalescing::test_scatter_tracked Tracking gets disconnected from original message
============================================== 428 passed, 42 skipped, 1 xfailed, 8 xpassed, 14 warnings in 460.09s (0:07:40) ==============================================
```

**Comment by minrk** [comment]
Yeah, the benchmarks directory doesn't contain any tests, though pytest finds one file to check. Try `pytest --pyargs ipyparallel` to run it against the installed package.

Sounds like everything passes in the real tests, though, which is great!
