### ISSUE TITLE
TaskScheduler raises a TraitError when logging is forwarded to a url using 0MQ

### ISSUE THREAD

**Issue by bheklilr** [ipython/ipyparallel#58]
Using the following package versions installed with conda on Windows 7 64bit

Package      | Version
-------------|--------
python       | 2.7.10
ipykernel    | 4.0.3
ipyparallel  | 4.0.2
ipython      | 4.0.0
jupyter_core | 4.0.4
pyzmq        | 14.7.0
setuptools   | 18.4
traitlets    | 4.0.0

With `IPython.sys_info()`:

    {'commit_hash': u'f534027',
     'commit_source': 'installation',
     'default_encoding': 'cp437',
     'ipython_path': 'C:\\Users\\bheklilr\\AppData\\Local\\Continuum\\Miniconda3\\envs\\quick\\lib\\site-packages\\IPython',
     'ipython_version': '4.0.0',
     'os_name': 'nt',
     'platform': 'Windows-7-6.1.7601-SP1',
     'sys_executable': 'C:\\Users\\bheklilr\\AppData\\Local\\Continuum\\Miniconda3\\envs\\quick\\python.exe',
     'sys_platform': 'win32',
     'sys_version': '2.7.10 |Continuum Analytics, Inc.| (default, Sep 15 2015, 14:26:14) [MSC v.1500 64 bit (AMD64)]'}

If I run

    ipcontroller start --IPControllerApp.log_url=tcp://127.0.0.1:12345

I see the logging message

    2015-10-26 15:52:22.441 [IPControllerApp] Forwarding logging to tcp://127.0.0.1:12345

and then after the pid file is created I get the error message

    Process Process-1:
    Traceback (most recent call last):
      File "C:\Users\bheklilr\AppData\Local\Continuum\Miniconda3\envs\quick\lib\multiprocessing\process.py", line 258, in _bootstrap
        self.run()
      File "C:\Users\bheklilr\AppData\Local\Continuum\Miniconda3\envs\quick\lib\multiprocessing\process.py", line 114, in run
        self._target(*self._args, **self._kwargs)
      File "C:\Users\bheklilr\AppData\Local\Continuum\Miniconda3\envs\quick\lib\site-packages\ipyparallel\controller\scheduler.py", line 842, in launch_scheduler
        config=config)
      File "C:\Users\bheklilr\AppData\Local\Continuum\Miniconda3\envs\quick\lib\site-packages\jupyter_client\session.py", line 169, in __init__
        super(SessionFactory, self).__init__(**kwargs)
      File "C:\Users\bheklilr\AppData\Local\Continuum\Miniconda3\envs\quick\lib\site-packages\traitlets\config\configurable.py", line 74, in __init__
        super(Configurable, self).__init__(**kwargs)
      File "C:\Users\bheklilr\AppData\Local\Continuum\Miniconda3\envs\quick\lib\site-packages\traitlets\traitlets.py", line 588, in __init__
        setattr(self, key, value)
      File "C:\Users\bheklilr\AppData\Local\Continuum\Miniconda3\envs\quick\lib\site-packages\traitlets\traitlets.py", line 450, in __set__
        new_value = self._validate(obj, value)
      File "C:\Users\bheklilr\AppData\Local\Continuum\Miniconda3\envs\quick\lib\site-packages\traitlets\traitlets.py", line 471, in _validate
        value = self.validate(obj, value)
      File "C:\Users\bheklilr\AppData\Local\Continuum\Miniconda3\envs\quick\lib\site-packages\traitlets\traitlets.py", line 1045, in validate
        self.error(obj, value)
      File "C:\Users\bheklilr\AppData\Local\Continuum\Miniconda3\envs\quick\lib\site-packages\traitlets\traitlets.py", line 899, in error
        raise TraitError(e)
    TraitError: The 'log' trait of a TaskScheduler instance must be a Logger, but a value of type 'NoneType' (i.e. None) was specified.

And I don't actually seem to get log messages forwarded to that URL using the code

    from __future__ import print_function

    import time
    import threading
    import subprocess
    import zmq
    from zmq.eventloop import ioloop, zmqstream

    class Log(object):
        def __init__(self, url):
            self.url = url

            self.ctx = zmq.Context()

            self.lock = threading.Lock()
            self._messages = []

        def log_message(self, msg):
            print('Got message: {}'.format(msg))
            with self.lock:
                self._messages.append(msg)

        @property
        def messages(self):
            with self.lock:
                return self._messages[:]

        def start_listening(self):
            self.socket = self.ctx.socket(zmq.SUB)
            self.socket.bind(self.url)

            self.loop = ioloop.IOLoop().instance()
            self.stream = zmqstream.ZMQStream(self.socket, self.loop)

            self.stream.on_recv(self.log_message)

            self.loop_thread = threading.Thread(target=self.loop.start)
            self.loop_thread.daemon = True
            self.loop_thread.start()

        def stop_listening(self):
            self.loop.stop()
            self.loop_thread.join()
            self.socket.unbind(self.url)

    l = Log('tcp://127.0.0.1:12345')
    l.start_listening()

    p = subprocess.Popen(['ipcontroller', '--IPControllerApp.log_url=tcp://127.0.0.1:12345'],
                         stdout=subprocess.PIPE, stderr=subprocess.PIPE)

    time.sleep(10)

    p.terminate()
    p.wait()

    print(l.messages)

I may be using `zmq` incorrectly, I don't really have much experience with it, but regardless it seems like there's a bug in ipyparallel when configuring the `IPControllerApp.log_url` that shouldn't be there.  I did try putting this in my profile's `ipcontroller_config.py` file but I get the same behavior as when specifying it from the command line, so at least it's working consistently.

**Comment by minrk** [comment]
Fixed by #59

**Comment by bheklilr** [comment]
@minrk Thanks!
