### ISSUE TITLE
Trying to start cluster trait error

### ISSUE THREAD

**Issue by dylan-alfi** [ipython/ipyparallel#736]
I keep trying to launch a cluster through both Jupyter notebook and the terminal interface. 
below is the output of the ipcluster start command. 

```
ipcluster start -n 1 --debug
2022-08-04 17:43:25.240 [IPClusterStart] IPYTHONDIR set to: /home/dylan/.ipython
2022-08-04 17:43:25.241 [IPClusterStart] Using existing profile dir: '/home/dylan/.ipython/profile_default'
2022-08-04 17:43:25.241 [IPClusterStart] Searching path ['/home/dylan', '/home/dylan/.ipython/profile_default', '/usr/etc/ipython', '/usr/local/etc/ipython', '/etc/ipython'] for config files
2022-08-04 17:43:25.241 [IPClusterStart] Attempting to load config file: ipython_config.py
2022-08-04 17:43:25.241 [IPClusterStart] Looking for ipython_config in /etc/ipython
2022-08-04 17:43:25.241 [IPClusterStart] Looking for ipython_config in /usr/local/etc/ipython
2022-08-04 17:43:25.241 [IPClusterStart] Looking for ipython_config in /usr/etc/ipython
2022-08-04 17:43:25.241 [IPClusterStart] Looking for ipython_config in /home/dylan/.ipython/profile_default
2022-08-04 17:43:25.241 [IPClusterStart] Loaded config file: /home/dylan/.ipython/profile_default/ipython_config.py
2022-08-04 17:43:25.241 [IPClusterStart] Looking for ipython_config in /home/dylan
2022-08-04 17:43:25.241 [IPClusterStart] Attempting to load config file: ipcluster_config.py
2022-08-04 17:43:25.241 [IPClusterStart] Looking for ipcluster_config in /etc/ipython
2022-08-04 17:43:25.241 [IPClusterStart] Looking for ipcluster_config in /usr/local/etc/ipython
2022-08-04 17:43:25.241 [IPClusterStart] Looking for ipcluster_config in /usr/etc/ipython
2022-08-04 17:43:25.241 [IPClusterStart] Looking for ipcluster_config in /home/dylan/.ipython/profile_default
2022-08-04 17:43:25.241 [IPClusterStart] Looking for ipcluster_config in /home/dylan
2022-08-04 17:43:25.242 [IPClusterStart] Forwarding SIGUSR1 to engines
2022-08-04 17:43:25.242 [IPClusterStart] Forwarding SIGUSR2 to engines
2022-08-04 17:43:25.242 [IPClusterStart] Not forwarding SIGINFO
2022-08-04 17:43:25.243 [IPClusterStart] Starting ipcluster with [daemonize=False]
2022-08-04 17:43:25.244 [IPClusterStart] Starting LocalControllerLauncher: ['/usr/bin/python3', '-m', 'ipyparallel.controller']
2022-08-04 17:43:25.244 [IPClusterStart] Sending output for ipcontroller-8096 to /home/dylan/.ipython/profile_default/log/ipcontroller-8096.log
2022-08-04 17:43:25.244 [IPClusterStart] Setting environment: IPP_CLUSTER_ID,IPP_PROFILE_DIR
2022-08-04 17:43:25.247 [IPClusterStart] LocalControllerLauncher /usr/bin/python3 started: 8099
2022-08-04 17:43:25.247 [IPClusterStart] Updating /home/dylan/.ipython/profile_default/security/cluster-.json
Traceback (most recent call last):
  File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/dylan/.local/lib/python3.8/site-packages/ipyparallel/controller/__main__.py", line 4, in <module>
    main()
  File "/home/dylan/.local/lib/python3.8/site-packages/ipyparallel/controller/app.py", line 1275, in main
    return IPController.launch_instance(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/traitlets/config/application.py", line 662, in launch_instance
    app = cls.instance(**kwargs)
  File "/usr/lib/python3/dist-packages/traitlets/config/configurable.py", line 412, in instance
    inst = cls(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/traitlets/traitlets.py", line 958, in __new__
    inst.setup_instance(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/traitlets/traitlets.py", line 986, in setup_instance
    super(HasTraits, self).setup_instance(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/traitlets/traitlets.py", line 977, in setup_instance
    value.instance_init(self)
  File "/usr/lib/python3/dist-packages/traitlets/traitlets.py", line 2266, in instance_init
    self._trait.instance_init(obj)
  File "/usr/lib/python3/dist-packages/traitlets/traitlets.py", line 522, in instance_init
    v = self._validate(obj, self.default_value)
  File "/usr/lib/python3/dist-packages/traitlets/traitlets.py", line 591, in _validate
    value = self.validate(obj, value)
  File "/usr/lib/python3/dist-packages/traitlets/traitlets.py", line 1871, in validate
    return _validate_bounds(self, obj, value)
  File "/usr/lib/python3/dist-packages/traitlets/traitlets.py", line 1840, in _validate_bounds
    raise TraitError(
traitlets.traitlets.TraitError: The value of the 'None' trait of an IPController instance should not be less than 1, but a value of 0 was specified
2022-08-04 17:43:25.620 [IPClusterStart] LocalControllerLauncher /usr/bin/python3 stopped: {'exit_code': 1, 'pid': 8099, 'identifier': 'ipcontroller-8096'}
2022-08-04 17:43:25.620 [IPClusterStart] Removing /home/dylan/.ipython/profile_default/log/ipcontroller-8096.log
2022-08-04 17:43:25.620 [IPClusterStart] Output for ipcontroller-8096:
Traceback (most recent call last):
  File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/dylan/.local/lib/python3.8/site-packages/ipyparallel/controller/__main__.py", line 4, in <module>
    main()
  File "/home/dylan/.local/lib/python3.8/site-packages/ipyparallel/controller/app.py", line 1275, in main
    return IPController.launch_instance(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/traitlets/config/application.py", line 662, in launch_instance
    app = cls.instance(**kwargs)
  File "/usr/lib/python3/dist-packages/traitlets/config/configurable.py", line 412, in instance
    inst = cls(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/traitlets/traitlets.py", line 958, in __new__
    inst.setup_instance(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/traitlets/traitlets.py", line 986, in setup_instance
    super(HasTraits, self).setup_instance(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/traitlets/traitlets.py", line 977, in setup_instance
    value.instance_init(self)
  File "/usr/lib/python3/dist-packages/traitlets/traitlets.py", line 2266, in instance_init
    self._trait.instance_init(obj)
  File "/usr/lib/python3/dist-packages/traitlets/traitlets.py", line 522, in instance_init
    v = self._validate(obj, self.default_value)
  File "/usr/lib/python3/dist-packages/traitlets/traitlets.py", line 591, in _validate
    value = self.validate(obj, value)
  File "/usr/lib/python3/dist-packages/traitlets/traitlets.py", line 1871, in validate
    return _validate_bounds(self, obj, value)
  File "/usr/lib/python3/dist-packages/traitlets/traitlets.py", line 1840, in _validate_bounds
    raise TraitError(
traitlets.traitlets.TraitError: The value of the 'None' trait of an IPController instance should not be less than 1, but a value of 0 was specified

2022-08-04 17:43:25.620 [IPClusterStart] WARNING | Controller stopped: {'exit_code': 1, 'pid': 8099, 'identifier': 'ipcontroller-8096'}
2022-08-04 17:43:25.620 [IPClusterStart] Removed cluster file: /home/dylan/.ipython/profile_default/security/cluster-.json
2022-08-04 17:43:26.274 [IPClusterStart] Setting $IPP_CONNECTION_INFO environment
2022-08-04 17:43:26.274 [IPClusterStart] Waiting for ['/home/dylan/.ipython/profile_default/security/ipcontroller-client.json', '/home/dylan/.ipython/profile_default/security/ipcontroller-engine.json']
2022-08-04 17:43:26.375 [IPClusterStart] Already notified stop (data)
ERROR:tornado.application:Exception in callback functools.partial(<function wrap.<locals>.null_wrapper at 0x7faa38be9ca0>, <Task finished name='Task-1' coro=<IPClusterStart.start_cluster() done, defined at /home/dylan/.local/lib/python3.8/site-packages/ipyparallel/cluster/app.py:568> exception=RuntimeError("Controller stopped with unknown while waiting for ['/home/dylan/.ipython/profile_default/security/ipcontroller-client.json', '/home/dylan/.ipython/profile_default/security/ipcontroller-engine.json']")>)
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/tornado/ioloop.py", line 758, in _run_callback
    ret = callback()
  File "/usr/lib/python3/dist-packages/tornado/stack_context.py", line 300, in null_wrapper
    return fn(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/tornado/ioloop.py", line 779, in _discard_future_result
    future.result()
  File "/home/dylan/.local/lib/python3.8/site-packages/ipyparallel/cluster/app.py", line 569, in start_cluster
    await self.cluster.start_cluster()
  File "/home/dylan/.local/lib/python3.8/site-packages/ipyparallel/cluster/cluster.py", line 780, in start_cluster
    await self.start_engines(n)
  File "/home/dylan/.local/lib/python3.8/site-packages/ipyparallel/cluster/cluster.py", line 698, in start_engines
    connection_info = await self.controller.get_connection_info()
  File "/home/dylan/.local/lib/python3.8/site-packages/ipyparallel/cluster/launcher.py", line 377, in get_connection_info
    raise RuntimeError(
RuntimeError: Controller stopped with unknown while waiting for ['/home/dylan/.ipython/profile_default/security/ipcontroller-client.json', '/home/dylan/.ipython/profile_default/security/ipcontroller-engine.json']
^C2022-08-04 17:43:36.605 [IPClusterStart] Received signal 2 received, stopping launchers...
2022-08-04 17:43:36.606 [IPClusterStart] ERROR | IPython cluster: stopping
2022-08-04 17:43:36.606 [IPClusterStart] Updating /home/dylan/.ipython/profile_default/security/cluster-.json
2022-08-04 17:43:36.607 [IPClusterStart] Stopping engine(s): 1659656606
2022-08-04 17:43:36.607 [IPClusterStart] Removed cluster file: /home/dylan/.ipython/profile_default/security/cluster-.json

raise TraitError(
traitlets.traitlets.TraitError: The value of the 'None' trait of an IPController instance should not be less than 1, but a value of 0 was specified
```

**Comment by minrk** [comment]
Sorry I missed this. That's certainly a strange error I haven't seen before. Can you share `pip list` and the OS, Python version? Do you have any configuration files in your default profile? If you haven't aready, can you check that packages are up-to-date, especially ipyparallel, traitlets, and ipykernel?

Does it work if you do e.g. `ipcluster start -n 1 --profile empty`?
