### ISSUE TITLE
Tutorial example throws exceptions "ResourceWarning: subprocess ... is still running"

### ISSUE THREAD

**Issue by tommedema** [ipython/ipyparallel#741]
I did a fresh install of ipyparallel and ran the example from the tutorial in a Jupyter notebook :

https://ipyparallel.readthedocs.io/en/stable/

```python
import time
import ipyparallel as ipp

task_durations = [1] * 25

# request a cluster
with ipp.Cluster(n = 4) as rc:
    # get a view on the cluster
    view = rc.load_balanced_view()
    # submit the tasks
    asyncresult = view.map_async(time.sleep, task_durations)
    # wait interactively for results
    asyncresult.wait_interactive()
    # retrieve actual results
    result = asyncresult.get()
```

Output:

```
Exception ignored in: <function Popen.__del__ at 0x7f7e28112f70>
Traceback (most recent call last):
  File "/Users/tommedema/opt/anaconda3/lib/python3.9/subprocess.py", line 1052, in __del__
    _warn("subprocess %s is still running" % self.pid,
ResourceWarning: subprocess 41586 is still running
Exception ignored in: <_io.FileIO name=95 mode='wb' closefd=True>
Traceback (most recent call last):
  File "/Users/tommedema/opt/anaconda3/lib/python3.9/site-packages/ipyparallel/cluster/launcher.py", line 665, in start
    return super().start()
ResourceWarning: unclosed file <_io.BufferedWriter name=95>
Starting 4 engines with <class 'ipyparallel.cluster.launcher.LocalEngineSetLauncher'>
Exception ignored in: <function Popen.__del__ at 0x7f7e28112f70>
Traceback (most recent call last):
  File "/Users/tommedema/opt/anaconda3/lib/python3.9/subprocess.py", line 1052, in __del__
    _warn("subprocess %s is still running" % self.pid,
ResourceWarning: subprocess 41600 is still running
Exception ignored in: <_io.FileIO name=97 mode='wb' closefd=True>
Traceback (most recent call last):
  File "/Users/tommedema/opt/anaconda3/lib/python3.9/site-packages/ipyparallel/cluster/launcher.py", line 749, in start
    d = el.start()
ResourceWarning: unclosed file <_io.BufferedWriter name=97>
Exception ignored in: <function Popen.__del__ at 0x7f7e28112f70>
Traceback (most recent call last):
  File "/Users/tommedema/opt/anaconda3/lib/python3.9/subprocess.py", line 1052, in __del__
    _warn("subprocess %s is still running" % self.pid,
ResourceWarning: subprocess 41601 is still running
Exception ignored in: <_io.FileIO name=97 mode='wb' closefd=True>
Traceback (most recent call last):
  File "/Users/tommedema/opt/anaconda3/lib/python3.9/site-packages/ipyparallel/cluster/launcher.py", line 749, in start
    d = el.start()
ResourceWarning: unclosed file <_io.BufferedWriter name=97>
Exception ignored in: <function Popen.__del__ at 0x7f7e28112f70>
Traceback (most recent call last):
  File "/Users/tommedema/opt/anaconda3/lib/python3.9/subprocess.py", line 1052, in __del__
    _warn("subprocess %s is still running" % self.pid,
ResourceWarning: subprocess 41602 is still running
Exception ignored in: <_io.FileIO name=97 mode='wb' closefd=True>
Traceback (most recent call last):
  File "/Users/tommedema/opt/anaconda3/lib/python3.9/site-packages/ipyparallel/cluster/launcher.py", line 749, in start
    d = el.start()
ResourceWarning: unclosed file <_io.BufferedWriter name=97>
Exception ignored in: <function Popen.__del__ at 0x7f7e28112f70>
Traceback (most recent call last):
  File "/Users/tommedema/opt/anaconda3/lib/python3.9/subprocess.py", line 1052, in __del__
    _warn("subprocess %s is still running" % self.pid,
ResourceWarning: subprocess 41603 is still running
Exception ignored in: <_io.FileIO name=97 mode='wb' closefd=True>
Traceback (most recent call last):
  File "/Users/tommedema/opt/anaconda3/lib/python3.9/site-packages/ipyparallel/cluster/launcher.py", line 749, in start
    d = el.start()
ResourceWarning: unclosed file <_io.BufferedWriter name=97>
100%
4/4 [00:06<00:00, 6.02s/engine]
sleep: 100%
25/25 [00:07<00:00, 3.17tasks/s]
Stopping engine(s): 1661715279
engine set stopped 1661715279: {'engines': {'0': {'exit_code': 0, 'pid': 41600, 'identifier': '0'}, '1': {'exit_code': 0, 'pid': 41601, 'identifier': '1'}, '2': {'exit_code': 0, 'pid': 41602, 'identifier': '2'}, '3': {'exit_code': 0, 'pid': 41603, 'identifier': '3'}}, 'exit_code': 0}
Stopping controller
Controller stopped: {'exit_code': 0, 'pid': 41586, 'identifier': 'ipcontroller-1661715278-frh9-39986'}
```

Versions:
The version of the notebook server is: 6.4.5
The server is running on this version of Python:
Python 3.9.7 (default, Sep 16 2021, 08:50:36) 
[Clang 10.0.0 ]
IPython 7.29.0

Running on MacOS Monterey 12.5.

**Comment by minrk** [comment]
Thanks! These are warnings, not exceptions, but they should be suppressed by #744
