### ISSUE TITLE
ValueError: buffer source array is read-only

### ISSUE THREAD

**Issue by tommedema** [ipython/ipyparallel#742]
First off, great library. Thank you!

I setup ipyparallel to compute the dynamic time warping distance between time series on multiple processors in parallel.

This is working great:

```python
import ipyparallel as ipp
import os
    
clusterProcessesCount = os.cpu_count()

cluster = ipp.Cluster(n = clusterProcessesCount)
cluster.start_cluster_sync()
rc = cluster.connect_client_sync()
rc.wait_for_engines(clusterProcessesCount)
lview = rc.load_balanced_view()
dview = rc[:]

for result in lview.imap(parallelTrainTestQuery, queries, ordered = False, max_outstanding = 'auto'):
    # store the result
```

where parallelTrainTestQuery calls [dtaidistance](https://dtaidistance.readthedocs.io/):

```python
from dtaidistance.subsequence.dtw import subsequence_search

subsequence_search(q, series, dists_options={'use_c': False})
```

However, this version without c is about 300 times slower than the version with c, and so I have to use the C optimized version with `dists_options={'use_c': True}`. The C version works fine without ipyparallel, but as soon as I run it from an ipyparallel child process I get this:

```
[14:apply]
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<string> in <module>

/var/folders/lm/xhqw06kd341ck445l0rpz_cr0000gn/T/ipykernel_5397/1226334596.py in parallelTrainTestQuery(q)

/var/folders/lm/xhqw06kd341ck445l0rpz_cr0000gn/T/ipykernel_5397/1226334596.py in getQuerySeriesResults(q, series, additions, minMatchCount, maxMatchCount)

~/opt/anaconda3/lib/python3.9/site-packages/dtaidistance/subsequence/dtw.py in kbest_matches(self, k)
    557 
    558     def kbest_matches(self, k=1):
--> 559         self.align(k=k)
    560         if k is None:
    561             return [SSMatch(best_idx, self) for best_idx in range(len(self.distances))]

~/opt/anaconda3/lib/python3.9/site-packages/dtaidistance/subsequence/dtw.py in align(self, k)
    530         max_dist = np.inf
    531         for idx, series in enumerate(self.s):
--> 532             dist = dtw.distance(self.query, series, **self.dists_options)
    533             if k is not None:
    534                 if len(h) < k:

~/opt/anaconda3/lib/python3.9/site-packages/dtaidistance/dtw.py in distance(s1, s2, window, max_dist, max_step, max_length_diff, penalty, psi, use_c, use_pruning, only_ub)
    176             logger.warning("C-library not available, using the Python version")
    177         else:
--> 178             return distance_fast(s1, s2, window,
    179                                  max_dist=max_dist,
    180                                  max_step=max_step,

~/opt/anaconda3/lib/python3.9/site-packages/dtaidistance/dtw.py in distance_fast(s1, s2, window, max_dist, max_step, max_length_diff, penalty, psi, use_pruning, only_ub)
    293     s2 = util_numpy.verify_np_array(s2)
    294     # Move data to C library
--> 295     d = dtw_cc.distance(s1, s2,
    296                         window=window,
    297                         max_dist=max_dist,

~/opt/anaconda3/lib/python3.9/site-packages/dtaidistance/dtw_cc.pyx in dtaidistance.dtw_cc.distance()

~/opt/anaconda3/lib/python3.9/site-packages/dtaidistance/dtw_cc.cpython-39-darwin.so in View.MemoryView.memoryview_cwrapper()

~/opt/anaconda3/lib/python3.9/site-packages/dtaidistance/dtw_cc.cpython-39-darwin.so in View.MemoryView.memoryview.__cinit__()

ValueError: buffer source array is read-only

exception calling callback for <AsyncResult(<ipyparallel.serialize.serialize.PrePickled object at 0x7fd1a1370040>): failed>
Traceback (most recent call last):
  File "/Users/tommedema/opt/anaconda3/lib/python3.9/site-packages/ipyparallel/client/asyncresult.py", line 528, in _resolve_result
    raise r
ipyparallel.error.RemoteError: [13:apply] ValueError: buffer source array is read-only

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/tommedema/opt/anaconda3/lib/python3.9/concurrent/futures/_base.py", line 329, in _invoke_callbacks
    callback(self)
  File "/Users/tommedema/opt/anaconda3/lib/python3.9/site-packages/ipyparallel/client/view.py", line 1458, in consume_callback
    consumer_pool.submit(consume_next)
  File "/Users/tommedema/opt/anaconda3/lib/python3.9/concurrent/futures/thread.py", line 161, in submit
    raise RuntimeError('cannot schedule new futures after shutdown')
RuntimeError: cannot schedule new futures after shutdown
exception calling callback for <AsyncResult(<ipyparallel.serialize.serialize.PrePickled object at 0x7fd1a1370040>): failed>
Traceback (most recent call last):
  File "/Users/tommedema/opt/anaconda3/lib/python3.9/site-packages/ipyparallel/client/asyncresult.py", line 528, in _resolve_result
    raise r
ipyparallel.error.RemoteError: [7:apply] ValueError: buffer source array is read-only

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/tommedema/opt/anaconda3/lib/python3.9/concurrent/futures/_base.py", line 329, in _invoke_callbacks
    callback(self)
  File "/Users/tommedema/opt/anaconda3/lib/python3.9/site-packages/ipyparallel/client/view.py", line 1458, in consume_callback
    consumer_pool.submit(consume_next)
  File "/Users/tommedema/opt/anaconda3/lib/python3.9/concurrent/futures/thread.py", line 161, in submit
    raise RuntimeError('cannot schedule new futures after shutdown')
RuntimeError: cannot schedule new futures after shutdown
exception calling callback for <AsyncResult(<ipyparallel.serialize.serialize.PrePickled object at 0x7fd1a1370040>): failed>
Traceback (most recent call last):
  File "/Users/tommedema/opt/anaconda3/lib/python3.9/site-packages/ipyparallel/client/asyncresult.py", line 528, in _resolve_result
    raise r
ipyparallel.error.RemoteError: [6:apply] ValueError: buffer source array is read-only

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/tommedema/opt/anaconda3/lib/python3.9/concurrent/futures/_base.py", line 329, in _invoke_callbacks
    callback(self)
  File "/Users/tommedema/opt/anaconda3/lib/python3.9/site-packages/ipyparallel/client/view.py", line 1458, in consume_callback
    consumer_pool.submit(consume_next)
  File "/Users/tommedema/opt/anaconda3/lib/python3.9/concurrent/futures/thread.py", line 161, in submit
    raise RuntimeError('cannot schedule new futures after shutdown')
RuntimeError: cannot schedule new futures after shutdown
exception calling callback for <AsyncResult(<ipyparallel.serialize.serialize.PrePickled object at 0x7fd1a1370040>): failed>
Traceback (most recent call last):
  File "/Users/tommedema/opt/anaconda3/lib/python3.9/site-packages/ipyparallel/client/asyncresult.py", line 528, in _resolve_result
    raise r
ipyparallel.error.RemoteError: [4:apply] ValueError: buffer source array is read-only

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/tommedema/opt/anaconda3/lib/python3.9/concurrent/futures/_base.py", line 329, in _invoke_callbacks
    callback(self)
  File "/Users/tommedema/opt/anaconda3/lib/python3.9/site-packages/ipyparallel/client/view.py", line 1458, in consume_callback
    consumer_pool.submit(consume_next)
  File "/Users/tommedema/opt/anaconda3/lib/python3.9/concurrent/futures/thread.py", line 161, in submit
    raise RuntimeError('cannot schedule new futures after shutdown')
RuntimeError: cannot schedule new futures after shutdown
exception calling callback for <AsyncResult(<ipyparallel.serialize.serialize.PrePickled object at 0x7fd1a1370040>): failed>
Traceback (most recent call last):
  File "/Users/tommedema/opt/anaconda3/lib/python3.9/site-packages/ipyparallel/client/asyncresult.py", line 528, in _resolve_result
    raise r
ipyparallel.error.RemoteError: [1:apply] ValueError: buffer source array is read-only

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/tommedema/opt/anaconda3/lib/python3.9/concurrent/futures/_base.py", line 329, in _invoke_callbacks
    callback(self)
  File "/Users/tommedema/opt/anaconda3/lib/python3.9/site-packages/ipyparallel/client/view.py", line 1458, in consume_callback
    consumer_pool.submit(consume_next)
  File "/Users/tommedema/opt/anaconda3/lib/python3.9/concurrent/futures/thread.py", line 161, in submit
    raise RuntimeError('cannot schedule new futures after shutdown')
RuntimeError: cannot schedule new futures after shutdown
exception calling callback for <AsyncResult(<ipyparallel.serialize.serialize.PrePickled object at 0x7fd1a1370040>): failed>
Traceback (most recent call last):
  File "/Users/tommedema/opt/anaconda3/lib/python3.9/site-packages/ipyparallel/client/asyncresult.py", line 528, in _resolve_result
    raise r
ipyparallel.error.RemoteError: [3:apply] ValueError: buffer source array is read-only

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/tommedema/opt/anaconda3/lib/python3.9/concurrent/futures/_base.py", line 329, in _invoke_callbacks
    callback(self)
  File "/Users/tommedema/opt/anaconda3/lib/python3.9/site-packages/ipyparallel/client/view.py", line 1458, in consume_callback
    consumer_pool.submit(consume_next)
  File "/Users/tommedema/opt/anaconda3/lib/python3.9/concurrent/futures/thread.py", line 161, in submit
    raise RuntimeError('cannot schedule new futures after shutdown')
RuntimeError: cannot schedule new futures after shutdown
exception calling callback for <AsyncResult(<ipyparallel.serialize.serialize.PrePickled object at 0x7fd1a1370040>): failed>
Traceback (most recent call last):
  File "/Users/tommedema/opt/anaconda3/lib/python3.9/site-packages/ipyparallel/client/asyncresult.py", line 528, in _resolve_result
    raise r
ipyparallel.error.RemoteError: [10:apply] ValueError: buffer source array is read-only

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/tommedema/opt/anaconda3/lib/python3.9/concurrent/futures/_base.py", line 329, in _invoke_callbacks
    callback(self)
  File "/Users/tommedema/opt/anaconda3/lib/python3.9/site-packages/ipyparallel/client/view.py", line 1458, in consume_callback
    consumer_pool.submit(consume_next)
  File "/Users/tommedema/opt/anaconda3/lib/python3.9/concurrent/futures/thread.py", line 161, in submit
    raise RuntimeError('cannot schedule new futures after shutdown')
RuntimeError: cannot schedule new futures after shutdown
exception calling callback for <AsyncResult(<ipyparallel.serialize.serialize.PrePickled object at 0x7fd1a1370040>): failed>
Traceback (most recent call last):
  File "/Users/tommedema/opt/anaconda3/lib/python3.9/site-packages/ipyparallel/client/asyncresult.py", line 528, in _resolve_result
    raise r
ipyparallel.error.RemoteError: [11:apply] ValueError: buffer source array is read-only

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/tommedema/opt/anaconda3/lib/python3.9/concurrent/futures/_base.py", line 329, in _invoke_callbacks
    callback(self)
  File "/Users/tommedema/opt/anaconda3/lib/python3.9/site-packages/ipyparallel/client/view.py", line 1458, in consume_callback
    consumer_pool.submit(consume_next)
  File "/Users/tommedema/opt/anaconda3/lib/python3.9/concurrent/futures/thread.py", line 161, in submit
    raise RuntimeError('cannot schedule new futures after shutdown')
RuntimeError: cannot schedule new futures after shutdown
exception calling callback for <AsyncResult(<ipyparallel.serialize.serialize.PrePickled object at 0x7fd1a1370040>): failed>
Traceback (most recent call last):
  File "/Users/tommedema/opt/anaconda3/lib/python3.9/site-packages/ipyparallel/client/asyncresult.py", line 528, in _resolve_result
    raise r
ipyparallel.error.RemoteError: [2:apply] ValueError: buffer source array is read-only

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/tommedema/opt/anaconda3/lib/python3.9/concurrent/futures/_base.py", line 329, in _invoke_callbacks
    callback(self)
  File "/Users/tommedema/opt/anaconda3/lib/python3.9/site-packages/ipyparallel/client/view.py", line 1458, in consume_callback
    consumer_pool.submit(consume_next)
  File "/Users/tommedema/opt/anaconda3/lib/python3.9/concurrent/futures/thread.py", line 161, in submit
    raise RuntimeError('cannot schedule new futures after shutdown')
RuntimeError: cannot schedule new futures after shutdown
exception calling callback for <AsyncResult(<ipyparallel.serialize.serialize.PrePickled object at 0x7fd1a1370040>): failed>
Traceback (most recent call last):
  File "/Users/tommedema/opt/anaconda3/lib/python3.9/site-packages/ipyparallel/client/asyncresult.py", line 528, in _resolve_result
    raise r
ipyparallel.error.RemoteError: [0:apply] ValueError: buffer source array is read-only

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/tommedema/opt/anaconda3/lib/python3.9/concurrent/futures/_base.py", line 329, in _invoke_callbacks
    callback(self)
  File "/Users/tommedema/opt/anaconda3/lib/python3.9/site-packages/ipyparallel/client/view.py", line 1458, in consume_callback
    consumer_pool.submit(consume_next)
  File "/Users/tommedema/opt/anaconda3/lib/python3.9/concurrent/futures/thread.py", line 161, in submit
    raise RuntimeError('cannot schedule new futures after shutdown')
RuntimeError: cannot schedule new futures after shutdown
exception calling callback for <AsyncResult(<ipyparallel.serialize.serialize.PrePickled object at 0x7fd1a1370040>): failed>
Traceback (most recent call last):
  File "/Users/tommedema/opt/anaconda3/lib/python3.9/site-packages/ipyparallel/client/asyncresult.py", line 528, in _resolve_result
    raise r
ipyparallel.error.RemoteError: [5:apply] ValueError: buffer source array is read-only

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/tommedema/opt/anaconda3/lib/python3.9/concurrent/futures/_base.py", line 329, in _invoke_callbacks
    callback(self)
  File "/Users/tommedema/opt/anaconda3/lib/python3.9/site-packages/ipyparallel/client/view.py", line 1458, in consume_callback
    consumer_pool.submit(consume_next)
  File "/Users/tommedema/opt/anaconda3/lib/python3.9/concurrent/futures/thread.py", line 161, in submit
    raise RuntimeError('cannot schedule new futures after shutdown')
RuntimeError: cannot schedule new futures after shutdown
exception calling callback for <AsyncResult(<ipyparallel.serialize.serialize.PrePickled object at 0x7fd1a1370040>): failed>
Traceback (most recent call last):
  File "/Users/tommedema/opt/anaconda3/lib/python3.9/site-packages/ipyparallel/client/asyncresult.py", line 528, in _resolve_result
    raise r
ipyparallel.error.RemoteError: [9:apply] ValueError: buffer source array is read-only

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/tommedema/opt/anaconda3/lib/python3.9/concurrent/futures/_base.py", line 329, in _invoke_callbacks
    callback(self)
  File "/Users/tommedema/opt/anaconda3/lib/python3.9/site-packages/ipyparallel/client/view.py", line 1458, in consume_callback
    consumer_pool.submit(consume_next)
  File "/Users/tommedema/opt/anaconda3/lib/python3.9/concurrent/futures/thread.py", line 161, in submit
    raise RuntimeError('cannot schedule new futures after shutdown')
RuntimeError: cannot schedule new futures after shutdown
exception calling callback for <AsyncResult(<ipyparallel.serialize.serialize.PrePickled object at 0x7fd1a1370040>): failed>
Traceback (most recent call last):
  File "/Users/tommedema/opt/anaconda3/lib/python3.9/site-packages/ipyparallel/client/asyncresult.py", line 528, in _resolve_result
    raise r
ipyparallel.error.RemoteError: [14:apply] ValueError: buffer source array is read-only

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/tommedema/opt/anaconda3/lib/python3.9/concurrent/futures/_base.py", line 329, in _invoke_callbacks
    callback(self)
  File "/Users/tommedema/opt/anaconda3/lib/python3.9/site-packages/ipyparallel/client/view.py", line 1458, in consume_callback
    consumer_pool.submit(consume_next)
  File "/Users/tommedema/opt/anaconda3/lib/python3.9/concurrent/futures/thread.py", line 161, in submit
    raise RuntimeError('cannot schedule new futures after shutdown')
RuntimeError: cannot schedule new futures after shutdown
exception calling callback for <AsyncResult(<ipyparallel.serialize.serialize.PrePickled object at 0x7fd1a1370040>): failed>
Traceback (most recent call last):
  File "/Users/tommedema/opt/anaconda3/lib/python3.9/site-packages/ipyparallel/client/asyncresult.py", line 528, in _resolve_result
    raise r
ipyparallel.error.RemoteError: [15:apply] ValueError: buffer source array is read-only

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/tommedema/opt/anaconda3/lib/python3.9/concurrent/futures/_base.py", line 329, in _invoke_callbacks
    callback(self)
  File "/Users/tommedema/opt/anaconda3/lib/python3.9/site-packages/ipyparallel/client/view.py", line 1458, in consume_callback
    consumer_pool.submit(consume_next)
  File "/Users/tommedema/opt/anaconda3/lib/python3.9/concurrent/futures/thread.py", line 161, in submit
    raise RuntimeError('cannot schedule new futures after shutdown')
RuntimeError: cannot schedule new futures after shutdown
exception calling callback for <AsyncResult(<ipyparallel.serialize.serialize.PrePickled object at 0x7fd1a1370040>): failed>
Traceback (most recent call last):
  File "/Users/tommedema/opt/anaconda3/lib/python3.9/site-packages/ipyparallel/client/asyncresult.py", line 528, in _resolve_result
    raise r
ipyparallel.error.RemoteError: [13:apply] ValueError: buffer source array is read-only

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/tommedema/opt/anaconda3/lib/python3.9/concurrent/futures/_base.py", line 329, in _invoke_callbacks
    callback(self)
  File "/Users/tommedema/opt/anaconda3/lib/python3.9/site-packages/ipyparallel/client/view.py", line 1458, in consume_callback
    consumer_pool.submit(consume_next)
  File "/Users/tommedema/opt/anaconda3/lib/python3.9/concurrent/futures/thread.py", line 161, in submit
    raise RuntimeError('cannot schedule new futures after shutdown')
RuntimeError: cannot schedule new futures after shutdown
exception calling callback for <AsyncResult(<ipyparallel.serialize.serialize.PrePickled object at 0x7fd1a1370040>): failed>
Traceback (most recent call last):
  File "/Users/tommedema/opt/anaconda3/lib/python3.9/site-packages/ipyparallel/client/asyncresult.py", line 528, in _resolve_result
    raise r
ipyparallel.error.RemoteError: [12:apply] ValueError: buffer source array is read-only

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/tommedema/opt/anaconda3/lib/python3.9/concurrent/futures/_base.py", line 329, in _invoke_callbacks
    callback(self)
  File "/Users/tommedema/opt/anaconda3/lib/python3.9/site-packages/ipyparallel/client/view.py", line 1458, in consume_callback
    consumer_pool.submit(consume_next)
  File "/Users/tommedema/opt/anaconda3/lib/python3.9/concurrent/futures/thread.py", line 161, in submit
    raise RuntimeError('cannot schedule new futures after shutdown')
RuntimeError: cannot schedule new futures after shutdown
```

Is there anything I can do to help resolve this?

**Comment by tommedema** [comment]
Somehow the input query is not writable. I was able to resolve the issue by wrapping it with: `q = np.array(q)`. Even though it already was a numpy array (from np.take after to_numpy from pandas), which is weird, but at least it works now.

**Comment by minrk** [comment]
You're right - the underlying library (pyzmq) loads read-only buffers for safety when doing zero-copy to avoid memory corruption. You have to make a read-write copy if you want to modify arrays in-place.

I've since decided this is probably a mistake, but it can only be changed in pyzmq itself.
