### ISSUE TITLE
PBS template issue, no such file or directory

### ISSUE THREAD

**Issue by tanweihou** [ipython/ipyparallel#86]
I encounter something very similar that of issue #37 
I follow the guide here http://ipyparallel.readthedocs.org/en/stable/process.html#using-ipcluster-in-pbs-mode to setup ipython cluster in PBS mode

However, I could not start it and received the following error message
```
user@pc:~> ipcluster start --profile=pbs -n 1
2015-12-17 19:59:46.950 [IPClusterStart] Starting ipcluster with [daemon=False]
2015-12-17 19:59:46.951 [IPClusterStart] Creating pid file: /home/user/.ipython/profile_pbs/pid/ipcluster.pid
2015-12-17 19:59:46.952 [IPClusterStart] Starting Controller with PBS
2015-12-17 19:59:46.965 [IPClusterStart] ERROR | Controller start failed
Traceback (most recent call last):
  File "/myapps/anaconda/lib/python2.7/site-packages/ipyparallel/apps/ipclusterapp.py", line 503, in start_controller
    self.controller_launcher.start()
  File "/myapps/anaconda/lib/python2.7/site-packages/ipyparallel/apps/launcher.py", line 1203, in start
    return super(PBSControllerLauncher, self).start(1)
  File "/myapps/anaconda/lib/python2.7/site-packages/ipyparallel/apps/launcher.py", line 1151, in start
    output = check_output(self.args, env=os.environ)
  File "/myapps/anaconda/lib/python2.7/subprocess.py", line 566, in check_output
    process = Popen(stdout=PIPE, *popenargs, **kwargs)
  File "/myapps/anaconda/lib/python2.7/subprocess.py", line 710, in __init__
    errread, errwrite)
  File "/myapps/anaconda/lib/python2.7/subprocess.py", line 1335, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
ERROR:tornado.application:Exception in callback <functools.partial object at 0x7fffeeafc788>
Traceback (most recent call last):
  File "/myapps/anaconda/lib/python2.7/site-packages/tornado/ioloop.py", line 600, in _run_callback
    ret = callback()
  File "/myapps/anaconda/lib/python2.7/site-packages/tornado/stack_context.py", line 275, in null_wrapper
    return fn(*args, **kwargs)
  File "/myapps/anaconda/lib/python2.7/site-packages/ipyparallel/apps/ipclusterapp.py", line 548, in start
    self.start_controller()
  File "/myapps/anaconda/lib/python2.7/site-packages/ipyparallel/apps/ipclusterapp.py", line 503, in start_controller
    self.controller_launcher.start()
  File "/myapps/anaconda/lib/python2.7/site-packages/ipyparallel/apps/launcher.py", line 1203, in start
    return super(PBSControllerLauncher, self).start(1)
  File "/myapps/anaconda/lib/python2.7/site-packages/ipyparallel/apps/launcher.py", line 1151, in start
    output = check_output(self.args, env=os.environ)
  File "/myapps/anaconda/lib/python2.7/subprocess.py", line 566, in check_output
    process = Popen(stdout=PIPE, *popenargs, **kwargs)
  File "/myapps/anaconda/lib/python2.7/subprocess.py", line 710, in __init__
    errread, errwrite)
  File "/myapps/anaconda/lib/python2.7/subprocess.py", line 1335, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
```
I'm sure that it reads my PBS template file correctly (it prompted no such file error along with wrong path when I troubleshoot with some fake path)

Here is my PBS template file for both ipengine and ipcontroller
###### ipengine template
```
#PBS -V
#PBS -l walltime=8:00:00
#PBS -l nodes={n}:ppn=8
#PBS -j oe
#PBS -N ipcluster
#PBS -q myqueuename

cd $PBS_O_WORKDIR
mpiexec -n {n} ipengine --profile-dir={profile_dir}
```
##### ipcontroller template
```
#PBS -V
#PBS -l walltime=8:00:00
#PBS -l nodes={n}:ppn=8
#PBS -j oe
#PBS -N ipcluster
#PBS -q myqueuename

cd $PBS_O_WORKDIR
ipcontroller --profile-dir={profile_dir}
```
Ipython version 4.0.1
Ipyparallel version 4.1.0
Python 2.7.11

**Comment by minrk** [comment]
What do you get from `which -a qsub`?

**Comment by tanweihou** [comment]
```
user@pc:~> which -a qsub
/myapps/torque/5.1.1.2/bin/qsub
```
I use Environment Modules to manage software in my pc cluster, for some reasons it does not work if I load ``torque scheduler`` first then start ipcluster, it works fine if I explicitly load ``torque scheduler`` in the pbs template file.
Anyway, problem solved :) Thanks
